Repository Qui-Gon173/AiSD-2020, pull requests merged in 2020-10, with the labels that each got.

#5 Enilov d a lab0
  ИСТбд-22/Енилов Д.А/lab0/.vscode/tasks.json
  ИСТбд-22/Енилов Д.А/lab0/main.cpp
  ИСТбд-22/Енилов Д.А/lab0/отчет.md
Labels: Засчитано, ИСТбд-22

#3 ШаталовАВ lab0
  ИСТбд-21/Шаталов А.В/lab0/README.md
  ИСТбд-21/Шаталов А.В/lab0/main.cpp
Labels: ИСТбд-21

#1 МоисеевМГ Лаб0
  ИСТбд-21/Moiseev M. G/lab0/main.cpp
  ИСТбд-21/Moiseev M. G/lab0/report.md
Labels: ИСТбд-21

#6 Кольцов А. А. Лабы 0, 1 и 2. Добавил `.vscode` в `.gitignore`.
  .gitignore
  ИСТбд-21/KoltsovAA/lab0/README.md
  ИСТбд-21/KoltsovAA/lab0/main.cpp
  ИСТбд-21/KoltsovAA/lab1/README.md
  ИСТбд-21/KoltsovAA/lab1/main.cpp
  ИСТбд-21/KoltsovAA/lab2/README.md
  ИСТбд-21/KoltsovAA/lab2/main.cpp
Labels: ИСТбд-21, Ожидает проверки

#13 АбеляновДМ
  ИСТбд-21/AbeluanovDM/lab0/README.md
  ИСТбд-21/AbeluanovDM/lab0/main.cpp
Labels: ИСТбд-21, Ожидает проверки

#8 Tagashev i i
  ИСТбд-22/Tagashev I.I/lab0/lab0/main.cpp
  ИСТбд-22/Tagashev I.I/lab0/Отчёт.md
Labels: ИСТбд-22, Ожидает проверки

#9 Iskhakov e a
  ИСТбд-22/Iskhakov E A/lab0/main.cpp
  ИСТбд-22/Iskhakov E A/lab0/ОтчётЛабораторнаяработа№0.md
Labels: ИСТбд-22, Ожидает проверки

#19 Doronkin A.N
  ИСТбд-22/Doronkin A.N/lab0/main.cpp
  ИСТбд-22/Doronkin A.N/lab0/Отчет.md
Labels: ИСТбд-22, Ожидает проверки

#20 lab0 Egorov I. E.
  ИСТбд-22/Егоров И.Е/lab0/README.md
  ИСТбд-22/Егоров И.Е/lab0/main.cpp
Labels: ИСТбд-22, Ожидает проверки

#21 lab 0 Ушкова А.С
  ИСТбд-22/Ushkova A. S/lab0/helloworld.cpp
  ИСТбд-22/Ushkova A. S/lab0/отчет.md
Labels: Засчитано, ИСТбд-22

#7 Enilov D A lab1
  ИСТбд-22/Енилов Д.А/lab1/main.cpp
  ИСТбд-22/Енилов Д.А/lab1/отчет.md
Labels: ИСТбд-22, Ожидает проверки

#17 Бакунькина Н. М. Лаба 0
  ИСТбд-21/BakunkinaNM/lab0/main.cpp
  ИСТбд-21/BakunkinaNM/lab0/report.md
Labels: ИСТбд-21, Ожидает проверки

#22 Логинов Н.В., Лаб 0
  ИСТбд-21/Логинов Н.В/lab0/HelloWorld/HelloWorld.cbp
  ИСТбд-21/Логинов Н.В/lab0/HelloWorld/HelloWorld.layout
  ИСТбд-21/Логинов Н.В/lab0/HelloWorld/main.cpp
  ИСТбд-21/Логинов Н.В/lab0/Report.md
Labels: Засчитано, ИСТбд-21

#23 Ульянин А.А. добавил lab0
  ИСТбд-21/Ulianin A. A/lab0/laba0.cpp
  ИСТбд-21/Ulianin A. A/lab0/readMe.md
Labels: ИСТбд-21

#16 Кольцов А. Лабы 0, 1, 2
  ИСТбд-21/KoltsovAA/lab0/README.md
  ИСТбд-21/KoltsovAA/lab0/main.cpp
  ИСТбд-21/KoltsovAA/lab1/README.md
  ИСТбд-21/KoltsovAA/lab1/main.cpp
  ИСТбд-21/KoltsovAA/lab2/README.md
  ИСТбд-21/KoltsovAA/lab2/main.cpp
Labels: Засчитано, ИСТбд-21

#24 AbeluanovDM
  ИСТбд-21/AbeluanovDM/lab1/README.md
  ИСТбд-21/AbeluanovDM/lab1/main.cpp
Labels: Засчитано, ИСТбд-21

#18 Моисеев МГ Лаб1
  ИСТбд-21/Moiseev M. G/lab1/main.cpp
  ИСТбд-21/Moiseev M. G/lab1/report.md
Labels: Засчитано, ИСТбд-21

#26 Hodarev-D-A lab0
  README.md
  ИСТбд-22/Ходарев Д.А/lab0/README.md
  ИСТбд-22/Ходарев Д.А/lab0/main.cpp
Labels: Засчитано, ИСТбд-22

#27 Моисеев МГ Лаб2
  ИСТбд-21/Moiseev M. G/lab2/main.cpp
  ИСТбд-21/Moiseev M. G/lab2/report.md
Labels: Засчитано, ИСТбд-21

#33 Переименование каталогов
  ISTbd-21/AbeluanovDM/lab0/README.md
  ISTbd-21/AbeluanovDM/lab0/main.cpp
  ISTbd-21/AbeluanovDM/lab1/README.md
  ISTbd-21/AbeluanovDM/lab1/main.cpp
  ISTbd-21/BakunkinaNM/lab0/main.cpp
  ISTbd-21/BakunkinaNM/lab0/report.md
  ISTbd-21/KoltsovAA/lab0/README.md
  ISTbd-21/KoltsovAA/lab0/main.cpp
  ISTbd-21/KoltsovAA/lab1/README.md
  ISTbd-21/KoltsovAA/lab1/main.cpp
  ISTbd-21/KoltsovAA/lab2/README.md
  ISTbd-21/KoltsovAA/lab2/main.cpp
  ISTbd-21/Moiseev M. G/lab0/main.cpp
  ISTbd-21/Moiseev M. G/lab0/report.md
  ISTbd-21/Moiseev M. G/lab1/main.cpp
  ISTbd-21/Moiseev M. G/lab1/report.md
  ISTbd-21/Moiseev M. G/lab2/main.cpp
  ISTbd-21/Moiseev M. G/lab2/report.md
  ISTbd-21/Ulianin A. A/lab0/laba0.cpp
  ISTbd-21/Ulianin A. A/lab0/readMe.md
  ISTbd-21/Логинов Н.В/lab0/HelloWorld/HelloWorld.cbp
  ISTbd-21/Логинов Н.В/lab0/HelloWorld/HelloWorld.layout
  ISTbd-21/Логинов Н.В/lab0/HelloWorld/main.cpp
  ISTbd-21/Логинов Н.В/lab0/Report.md
  ISTbd-21/Шаталов А.В/lab0/README.md
  ISTbd-21/Шаталов А.В/lab0/main.cpp
  ISTbd-22/Doronkin A.N/lab0/main.cpp
  ISTbd-22/Doronkin A.N/lab0/Отчет.md
  ISTbd-22/Iskhakov E A/lab0/main.cpp
  ISTbd-22/Iskhakov E A/lab0/ОтчётЛабораторнаяработа№0.md
  ISTbd-22/Tagashev I.I/lab0/lab0/main.cpp
  ISTbd-22/Tagashev I.I/lab0/Отчёт.md
  ISTbd-22/Ushkova A. S/lab0/helloworld.cpp
  ISTbd-22/Ushkova A. S/lab0/отчет.md
  ISTbd-22/Егоров И.Е/lab0/README.md
  ISTbd-22/Егоров И.Е/lab0/main.cpp
  ISTbd-22/Енилов Д.А/lab0/main.cpp
  ISTbd-22/Енилов Д.А/lab0/отчет.md
  ISTbd-22/Енилов Д.А/lab1/main.cpp
  ISTbd-22/Енилов Д.А/lab1/отчет.md
  ISTbd-22/Саушкина Н. С/lab0/main.cpp
  ISTbd-22/Саушкина Н. С/lab0/report.md
  ISTbd-22/Ходарев Д.А/lab0/README.md
  ISTbd-22/Ходарев Д.А/lab0/main.cpp
  ИСТбд-22/Енилов Д.А/lab0/.vscode/tasks.json
Labels: Не по делу

#32 lab1-EgorovIE
  ИСТбд-22/Егоров И.Е/lab1/README.md
  ИСТбд-22/Егоров И.Е/lab1/main.cpp
Labels: Засчитано, ИСТбд-22

#34 lab0 Осипов К. С.
  ИСТбд-22/Осипов К.С/lab0/main.cpp
  ИСТбд-22/Осипов К.С/lab0/Отчёт.md
Labels: Засчитано, ИСТбд-22

#37 Add lab2
  ISTbd-21/AbeluanovDM/lab2/README.md
  ISTbd-21/AbeluanovDM/lab2/main.cpp
Labels: Засчитано, ИСТбд-21

#29 Tagashev I I - Lab1+Lab2
  ИСТбд-22/Tagashev I.I/lab1 + lab2/main.cpp
  ИСТбд-22/Tagashev I.I/lab1 + lab2/Отчёт_№1.md
  ИСТбд-22/Tagashev I.I/lab1/lab1/Source.cpp
  ИСТбд-22/Tagashev I.I/lab1/Отчёт_№1.md
Labels: ИСТбд-22, Ожидает проверки

#30 Iskhakov E A, lab1+lab2
  ИСТбд-22/Iskhakov E A/lab1+lab2/main.cpp
  ИСТбд-22/Iskhakov E A/lab1+lab2/Отчётклабораторнойработе№1.md
  ИСТбд-22/Iskhakov E A/lab1+lab2/Отчётклабораторнойработе№2.md
Labels: ИСТбд-22, Ожидает проверки

#41 replased labs to another folder
  ISTbd-22/Iskhakov E A/lab1+lab2/main.cpp
  ISTbd-22/Iskhakov E A/lab1+lab2/Отчётклабораторнойработе№1.md
  ISTbd-22/Iskhakov E A/lab1+lab2/Отчётклабораторнойработе№2.md
  ISTbd-22/Tagashev I.I/lab1 + lab2/main.cpp
  ISTbd-22/Tagashev I.I/lab1 + lab2/Отчёт_№1.md
  ISTbd-22/Tagashev I.I/lab1/lab1/Source.cpp
  ISTbd-22/Tagashev I.I/lab1/Отчёт_№1.md
  ISTbd-22/Егоров И.Е/lab1/README.md
  ISTbd-22/Егоров И.Е/lab1/main.cpp
  ISTbd-22/Осипов К.С/lab0/main.cpp
  ISTbd-22/Осипов К.С/lab0/Отчёт.md
Labels: Не по делу

#40 Enilov d a lab 2
  ISTbd-22/Ushkova A. S/lab0/helloworld.cpp
  ISTbd-22/Ushkova A. S/lab0/отчет.md
  ISTbd-22/Енилов Д.А/lab2/main.cpp
  ISTbd-22/Енилов Д.А/lab2/отчет.md
Labels: ИСТбд-22, Ожидает проверки

#43 added lab0
  ISTbd-22/Iskhakov T. I/lab0/main.cpp
  ISTbd-22/Iskhakov T. I/lab0/report.md
Labels: Засчитано, ИСТбд-22

#45 Гурьянов А.В., Лаб 0
  ISTbd-22/Гурьянов А.В/lab0/main.cpp
  ISTbd-22/Гурьянов А.В/lab0/readme.md
Labels: Засчитано, ИСТбд-22

#46 Tagashev Ivan lab3
  ISTbd-22/Tagashev I.I/lab3/Source.cpp
  ISTbd-22/Tagashev I.I/lab3/main.cpp
  ISTbd-22/Tagashev I.I/lab3/отчёт.md
Labels: ИСТбд-22, Ожидает проверки

#36 Doronkin A.N/lab1
  ISTbd-22/Doronkin A.N/lab1/main.cpp
  ISTbd-22/Doronkin A.N/lab1/Отчет.md
Labels: ИСТбд-22, На доработку

#50 Гурьянов Алексей Вячеславович, Лаб 1
  ISTbd-22/Гурьянов А.В/lab1/main.cpp
  ISTbd-22/Гурьянов А.В/lab1/readme.md
Labels: ИСТбд-22, Ожидает проверки

#47 Lab 1 Ushkova A.S
  ISTbd-22/Ushkova A. S/lab0/helloworld.cpp
  ISTbd-22/Ushkova A. S/lab1/poisksbarierrom.cpp
  ISTbd-22/Ushkova A. S/lab1/отчет.md
Labels: ИСТбд-22, На доработку
