Repository Qui-Gon173/AiSD-2020, pull requests merged in 2020-11, with the labels that each got.

#28 Саушкина Н. С./lab1
  ИСТбд-22/Саушкина Н. С/lab1/main.cpp
  ИСТбд-22/Саушкина Н. С/lab1/report.md
Labels: ИСТбд-22, На доработку

#60 replace labs
  ISTbd-22/Саушкина Н. С/lab1/main.cpp
  ISTbd-22/Саушкина Н. С/lab1/report.md
Labels: Не по делу

#38 lab 1
  ISTbd-21/Ulianin A. A/lab1/lab1.cpp
  ISTbd-21/Ulianin A. A/lab1/readMe.md
Labels: ИСТбд-21, На доработку, Ожидает проверки

#63 Гурьянов Алексей Вячеславович, Лаб 2
  ISTbd-22/Гурьянов А.В/lab2/main.cpp
  ISTbd-22/Гурьянов А.В/lab2/readme.md
Labels: Засчитано, ИСТбд-22

#49 add lab 0
  ISTbd-21/GilmetdinovaED/lab-0/lab-0.cbp
  ISTbd-21/GilmetdinovaED/lab-0/lab-0.layout
  ISTbd-21/GilmetdinovaED/lab-0/main.cpp
  ISTbd-21/GilmetdinovaED/lab-0/readme.md
Labels: ИСТбд-21, Ожидает проверки

#57 Abeluanov D M lab 3
  ISTbd-21/AbeluanovDM/lab3/README.md
  ISTbd-21/AbeluanovDM/lab3/main.cpp
Labels: Засчитано, ИСТбд-21

#70 deleted ИСТбд-22 folder
  ИСТбд-22/Егоров И.Е/lab1/README.md
  ИСТбд-22/Егоров И.Е/lab1/main.cpp
  ИСТбд-22/Осипов К.С/lab0/main.cpp
  ИСТбд-22/Осипов К.С/lab0/Отчёт.md
Labels: Не по делу

#71 add lab 0
  ISTbd-21/Kartashova M.V/lab-0/lab_0.cpp
  ISTbd-21/Kartashova M.V/lab-0/readMe.md
Labels: Засчитано, ИСТбд-21

#58 Abeluanov D M lab 4
  ISTbd-21/AbeluanovDM/lab4/README.md
  ISTbd-21/AbeluanovDM/lab4/main.cpp
Labels: Засчитано, ИСТбд-21

#59 Moiseev M G lab3
  ISTbd-21/Moiseev M. G/lab3/main.cpp
  ISTbd-21/Moiseev M. G/lab3/report.md
Labels: Засчитано, ИСТбд-21

#56 Ushkova A. S. lab2
  ISTbd-22/Ushkova A. S/lab2/selectionsort.cpp
  ISTbd-22/Ushkova A. S/lab2/отчет.md
Labels: Засчитано, ИСТбд-22

#64 Ushkova A S lab3
  ISTbd-22/Ushkova A. S/lab3/QuickSort.cpp
  ISTbd-22/Ushkova A. S/lab3/отчет.md
Labels: Засчитано, ИСТбд-22

#84 Ushkova A S lab4
  ISTbd-22/Ushkova A. S/lab4/heapSort.cpp
  ISTbd-22/Ushkova A. S/lab4/отчет.md
Labels: Засчитано, ИСТбд-22

#74 Гурьянов Алексей Вячеславович, Лаб 3
  ISTbd-22/Гурьянов А.В/lab3/main.cpp
  ISTbd-22/Гурьянов А.В/lab3/readme.md
Labels: Засчитано, ИСТбд-22

#65 Tagashev I I - Lab4
  ISTbd-22/Tagashev I.I/lab4/Source.cpp
  ISTbd-22/Tagashev I.I/lab4/отчёт.md
Labels: Засчитано, ИСТбд-22

#62 Кольцов. Лаба 4.
  ISTbd-21/KoltsovAA/lab4/README.rst
  ISTbd-21/KoltsovAA/lab4/main.cpp
Labels: ИСТбд-21, Ожидает проверки

#85 Add lab0
  ISTbd-21/PetrovaAA/lab0/Report0.md
  ISTbd-21/PetrovaAA/lab0/main.cpp
Labels: ИСТбд-21, Принято

#67 Кольцов. Лаба 5.
  ISTbd-21/KoltsovAA/lab5/README.rst
  ISTbd-21/KoltsovAA/lab5/main_external.cpp
  ISTbd-21/KoltsovAA/lab5/main_internal.cpp
Labels: ИСТбд-21, Принято

#81 Moiseev M G lab 4
  ISTbd-21/Moiseev M. G/lab4/main.cpp
  ISTbd-21/Moiseev M. G/lab4/report.md
Labels: ИСТбд-21, Принято

#79 Бакунькина Н. М. Лаба 1
  ISTbd-21/BakunkinaNM/lab1/main.cpp
  ISTbd-21/BakunkinaNM/lab1/report.md
Labels: ИСТбд-21, Принято

#73 Кольцов. Лаба 7.
  ISTbd-21/KoltsovAA/lab7/README.rst
  ISTbd-21/KoltsovAA/lab7/main.cpp
Labels: ИСТбд-21, Принято

#76 Abeluanov D M lab 5
  ISTbd-21/AbeluanovDM/lab5/README.md
  ISTbd-21/AbeluanovDM/lab5/array.txt
  ISTbd-21/AbeluanovDM/lab5/main_ext.cpp
  ISTbd-21/AbeluanovDM/lab5/main_int.cpp
Labels: ИСТбд-21, Принято

#72 Кольцов. Лаба 6.
  ISTbd-21/KoltsovAA/lab6/README.rst
  ISTbd-21/KoltsovAA/lab6/code_1.cpp
  ISTbd-21/KoltsovAA/lab6/code_2.cpp
  ISTbd-21/KoltsovAA/lab6/code_3.cpp
Labels: ИСТбд-21, Принято

#77 Abeluanov D M lab 6
  ISTbd-21/AbeluanovDM/lab6/README.md
  ISTbd-21/AbeluanovDM/lab6/main1.cpp
  ISTbd-21/AbeluanovDM/lab6/main2.cpp
  ISTbd-21/AbeluanovDM/lab6/main3.cpp
Labels: ИСТбд-21, Принято

#61 Кольцов А. Лаба 3. Еще раз.
  ISTbd-21/KoltsovAA/lab3/README.rst
  ISTbd-21/KoltsovAA/lab3/main.cpp
Labels: ИСТбд-21, Принято

#80 Бакунькина Н. М. Лаба 2
  ISTbd-21/BakunkinaNM/lab2/main.cpp
  ISTbd-21/BakunkinaNM/lab2/report.md
Labels: ИСТбд-21, Принято

#78 Abeluanov D M lab 7
  ISTbd-21/AbeluanovDM/lab7/README.md
  ISTbd-21/AbeluanovDM/lab7/main.cpp
Labels: ИСТбд-21, Принято

#83 add lab 2
  ISTbd-21/Ulianin A. A/lab2/lab2.cpp
  ISTbd-21/Ulianin A. A/lab2/readMe.md
Labels: ИСТбд-21, Принято

#69 Gilmetdinova add lab 1
  ISTbd-21/GilmetdinovaED/lab-1/lab-1.cbp
  ISTbd-21/GilmetdinovaED/lab-1/lab-1.depend
  ISTbd-21/GilmetdinovaED/lab-1/lab-1.layout
  ISTbd-21/GilmetdinovaED/lab-1/main.cpp
  ISTbd-21/GilmetdinovaED/lab-1/readme.md
Labels: ИСТбд-21, Принято

#91 add lab 3
  ISTbd-21/Ulianin A. A/lab3/lab3.cpp
  ISTbd-21/Ulianin A. A/lab3/readMe.md
Labels: ИСТбд-21, Принято

#87 EgorovIE_lab2
  ISTbd-22/Egorov I.E/lab2/lab2.cpp
  ISTbd-22/Egorov I.E/lab2/lab2.md
Labels: ИСТбд-22, На доработку

#86 Саушкина Н. С. лаб2
  ИСТбд-22/Саушкина Н. С/lab2/main.cpp
  ИСТбд-22/Саушкина Н. С/lab2/report.md
Labels: ИСТбд-22, На доработку

#89 Enilov-D-A-lab5
  ISTbd-22/Енилов Д.А/lab5/file.txt
  ISTbd-22/Енилов Д.А/lab5/main.cpp
  ISTbd-22/Енилов Д.А/lab5/отчет.md
Labels: ИСТбд-22, Принято

#94 перенес лабы в правильную папку, опять
  ISTbd-22/Саушкина Н. С/lab2/main.cpp
  ISTbd-22/Саушкина Н. С/lab2/report.md
Labels: Не по делу

#92 Saushkina-N-S/lab3
  ISTbd-22/Саушкина Н. С/lab3/main.cpp
  ISTbd-22/Саушкина Н. С/lab3/report.md
Labels: ИСТбд-22, Принято

#101 Enilov-D-A-lab6
  ISTbd-22/Енилов Д.А/lab6/main1.cpp
  ISTbd-22/Енилов Д.А/lab6/main2.cpp
  ISTbd-22/Енилов Д.А/lab6/main3.cpp
  ISTbd-22/Енилов Д.А/lab6/отчет.md
Labels: ИСТбд-22, Принято

#108 Enilov-D-A-lab7
  ISTbd-22/Енилов Д.А/lab7/main.cpp
  ISTbd-22/Енилов Д.А/lab7/отчет.md
Labels: ИСТбд-22, Ожидает проверки

#109 Гурьянов Алексей Вячеславович, Лаб 4
  ISTbd-22/Гурьянов А.В/lab3/main.cpp
  ISTbd-22/Гурьянов А.В/lab4/main.cpp
  ISTbd-22/Гурьянов А.В/lab4/readme.md
Labels: ИСТбд-22, Принято

#111 Doronkin.A.N lab 2
  ISTbd-22/Doronkin A.N/lab2/main.cpp
  ISTbd-22/Doronkin A.N/lab2/Отчет.md
Labels: ИСТбд-22, Ожидает проверки

#88 Kartashova M.V. lab-1
  ISTbd-21/Kartashova M.V/lab-1/lab-1.cpp
  ISTbd-21/Kartashova M.V/lab-1/report1.md
Labels: ИСТбд-21, Принято

#96 Moiseev M G lab 5
  ISTbd-21/Moiseev M. G/lab4/main.cpp
  ISTbd-21/Moiseev M. G/lab5/main.cpp
  ISTbd-21/Moiseev M. G/lab5/report.md
Labels: ИСТбд-21, Принято

#118 Petrova A.A., add lab1
  ISTbd-21/PetrovaAA/lab1/lab1.cpp
  ISTbd-21/PetrovaAA/lab1/report1.md
Labels: ИСТбд-21, Принято

#119 Petrova A.A., add lab2
  ISTbd-21/PetrovaAA/lab2/main.cpp
  ISTbd-21/PetrovaAA/lab2/report2.md
Labels: ИСТбд-21, Принято

#123 KashitsynaNA-lab-0
  ISTbd-21/KashitsynaNA/lab0/Hello_world.cpp
  ISTbd-21/KashitsynaNA/lab0/Отчет.md
Labels: ИСТбд-21, Принято

#100 Abeluanov D M lab 8.1
  ISTbd-21/AbeluanovDM/lab8.1/README.md
  ISTbd-21/AbeluanovDM/lab8.1/Vector.h
  ISTbd-21/AbeluanovDM/lab8.1/main.cpp
Labels: ИСТбд-21, Принято

#127 Loginov N V lab 1
  ISTbd-21/LoginovNV/lab0/HelloWorld/HelloWorld.cbp
  ISTbd-21/LoginovNV/lab0/HelloWorld/HelloWorld.layout
  ISTbd-21/LoginovNV/lab0/HelloWorld/main.cpp
  ISTbd-21/LoginovNV/lab0/Report.md
  ISTbd-21/LoginovNV/lab1/Report.md
  ISTbd-21/LoginovNV/lab1/main.cpp
Labels: ИСТбд-21, Принято

#128 Loginov N V lab 2
  ISTbd-21/Логинов Н.В/lab2/Report.md
  ISTbd-21/Логинов Н.В/lab2/main.cpp
Labels: ИСТбд-21, Принято

#129 Loginov N V lab 3
  ISTbd-21/Логинов Н.В/lab3/Report.md
  ISTbd-21/Логинов Н.В/lab3/main.cpp
Labels: ИСТбд-21, Принято

#130 Loginov N V lab 4
  ISTbd-21/Логинов Н.В/lab4/Report.md
  ISTbd-21/Логинов Н.В/lab4/main.cpp
Labels: ИСТбд-21, Принято

#131 Loginov N V lab 5
  ISTbd-21/LoginovNV/lab2/Report.md
  ISTbd-21/LoginovNV/lab2/main.cpp
  ISTbd-21/LoginovNV/lab3/Report.md
  ISTbd-21/LoginovNV/lab3/main.cpp
  ISTbd-21/LoginovNV/lab4/Report.md
  ISTbd-21/LoginovNV/lab4/main.cpp
  ISTbd-21/LoginovNV/lab5/Report.md
  ISTbd-21/LoginovNV/lab5/lab5.cpp
  ISTbd-21/LoginovNV/lab5/sortNumbers_1.txt
  ISTbd-21/LoginovNV/lab5/sortNumbers_2.txt
Labels: ИСТбд-21, Принято

#134 add lab 4
  ISTbd-21/Ulianin A. A/lab4/lab4.cpp
  ISTbd-21/Ulianin A. A/lab4/readMe.md
Labels: ИСТбд-21, Принято

#97 Moiseev M G lab 6
  ISTbd-21/Moiseev M. G/lab6/lab6_1.cpp
  ISTbd-21/Moiseev M. G/lab6/lab6_2.cpp
  ISTbd-21/Moiseev M. G/lab6/lab6_3.cpp
  ISTbd-21/Moiseev M. G/lab6/report.md
Labels: ИСТбд-21, Принято

#102 Moiseev M G lab 8.1
  ISTbd-21/Moiseev M. G/lab8.1/Stack.h
  ISTbd-21/Moiseev M. G/lab8.1/main.cpp
  ISTbd-21/Moiseev M. G/lab8.1/report.md
Labels: ИСТбд-21, Принято

#113 Moiseev M G lab 8.2
  ISTbd-21/Moiseev M. G/lab8.2/ArithmeticalGenerator.h
  ISTbd-21/Moiseev M. G/lab8.2/Func.h
  ISTbd-21/Moiseev M. G/lab8.2/Stack.h
  ISTbd-21/Moiseev M. G/lab8.2/StackIterator.h
  ISTbd-21/Moiseev M. G/lab8.2/main.cpp
  ISTbd-21/Moiseev M. G/lab8.2/report.md
Labels: ИСТбд-21, Принято

#125 Гурьянов Алексей Вячеславович, Лаб 7
  ISTbd-22/Гурьянов А.В/lab7/main.cpp
  ISTbd-22/Гурьянов А.В/lab7/readme.md
Labels: ИСТбд-22, Ожидает проверки, Принято

#126 Iskhakov T. I. lab 1
  ISTbd-22/Iskhakov T. I/lab1/main.cpp
  ISTbd-22/Iskhakov T. I/lab1/report.md
Labels: ИСТбд-22, Принято

#141 Ushkova A S lab6
  ISTbd-22/Ushkova A. S/lab6/1_программа.cpp
  ISTbd-22/Ushkova A. S/lab6/2_программа.cpp
  ISTbd-22/Ushkova A. S/lab6/3_программа.cpp
  ISTbd-22/Ushkova A. S/lab6/отчет.md
Labels: ИСТбд-22, На доработку

#145 Iskhakov T. I. lab 2
  ISTbd-22/Iskhakov T. I/lab2/main.cpp
  ISTbd-22/Iskhakov T. I/lab2/report.md
Labels: ИСТбд-22, Принято

#135 Iskhakov E A, lab3
  ИСТбд-22/Iskhakov E A/lab3/Source.cpp
  ИСТбд-22/Iskhakov E A/lab3/untitled.md
Labels: ИСТбд-22, Ожидает проверки

#138 Iskhakov E A, lab4
  ИСТбд-22/Iskhakov E A/lab4/main.cpp
  ИСТбд-22/Iskhakov E A/lab4/otchet.md
Labels: ИСТбд-22, Ожидает проверки

#146 Kuchina a a lab0
  ISTbd-22/Kuchina A. A/lab0/lab0.cpp
  ISTbd-22/Kuchina A. A/lab0/Отчет0.md
Labels: ИСТбд-22, Принято

#147 Кучина А. А. - Лаб1 и Лаб2
  ISTbd-22/Kuchina A. A/lab1+lab2/Source.cpp
  ISTbd-22/Kuchina A. A/lab1+lab2/Отчет.md
Labels: ИСТбд-22, Ожидает проверки

#150 [Hodarev-D-A] Снова переделал.
  ISTbd-22/Ходарев Д.А/lab1/README.md
  ISTbd-22/Ходарев Д.А/lab1/lab1.cpp
  ISTbd-22/Ходарев Д.А/lab2/README.md
  ISTbd-22/Ходарев Д.А/lab2/lab2.cpp
  ISTbd-22/Ходарев Д.А/lab3/README.md
  ISTbd-22/Ходарев Д.А/lab3/lab3.cpp
  ISTbd-22/Ходарев Д.А/lab4/README.md
  ISTbd-22/Ходарев Д.А/lab4/lab4.cpp
  ISTbd-22/Ходарев Д.А/lab6/README.md
  ISTbd-22/Ходарев Д.А/lab6/lab6.cpp
  ISTbd-22/Ходарев Д.А/lab7/README.md
  ISTbd-22/Ходарев Д.А/lab7/lab7.cpp
Labels: ИСТбд-22, Ожидает проверки

#99 Koltsov lab 8.1
  ISTbd-21/KoltsovAA/lab8.1/README.md
  ISTbd-21/KoltsovAA/lab8.1/Vector.h
  ISTbd-21/KoltsovAA/lab8.1/main.cpp
Labels: ИСТбд-21, Принято

#112 Koltsov lab 8.2
  ISTbd-21/KoltsovAA/lab8.2/ExpotentialGenerator.h
  ISTbd-21/KoltsovAA/lab8.2/README.md
  ISTbd-21/KoltsovAA/lab8.2/Vector.h
  ISTbd-21/KoltsovAA/lab8.2/VectorIterator.h
  ISTbd-21/KoltsovAA/lab8.2/main.cpp
  ISTbd-21/KoltsovAA/lab8.2/utils.h
Labels: ИСТбд-21, Принято

#104 Gilmetdinova add lab 2
  ISTbd-21/GilmetdinovaED/lab-2/lab-2.cbp
  ISTbd-21/GilmetdinovaED/lab-2/lab-2.depend
  ISTbd-21/GilmetdinovaED/lab-2/lab-2.layout
  ISTbd-21/GilmetdinovaED/lab-2/main.cpp
  ISTbd-21/GilmetdinovaED/lab-2/report.md
Labels: ИСТбд-21, Принято

#139 Loginov N V lab 6
  ISTbd-21/LoginovNV/lab6/Report.md
  ISTbd-21/LoginovNV/lab6/lab6_1.cpp
  ISTbd-21/LoginovNV/lab6/lab6_2.cpp
  ISTbd-21/LoginovNV/lab6/lab6_3.cpp
Labels: ИСТбд-21, Принято

#140 Loginov N V lab 7
  ISTbd-21/LoginovNV/lab7/Report.md
  ISTbd-21/LoginovNV/lab7/lab7.cpp
Labels: ИСТбд-21, Принято

#144 Бакунькина Н. М. Лаба 3
  ISTbd-21/BakunkinaNM/lab3/main.cpp
  ISTbd-21/BakunkinaNM/lab3/report.md
Labels: ИСТбд-21, Принято

#149 Petrova A.A., add lab3
  ISTbd-21/PetrovaAA/lab3/main.cpp
  ISTbd-21/PetrovaAA/lab3/report3.md
Labels: ИСТбд-21, Принято

#153 add lab 5
  ISTbd-21/Ulianin A. A/lab5/lab5.cpp
  ISTbd-21/Ulianin A. A/lab5/readMe.md
  ISTbd-21/Ulianin A. A/lab5/textSort.txt
Labels: ИСТбд-21, Принято

#154 Kartashova M add lab 3
  ISTbd-21/Kartashova M.V/lab-3/lab-3.cpp
  ISTbd-21/Kartashova M.V/lab-3/report3.md
Labels: ИСТбд-21, Принято

#155 Add lab0
  ISTbd-21/AlekseenkoDV/lab0/main.cpp
  ISTbd-21/AlekseenkoDV/lab0/readme.md
Labels: ИСТбд-21, Ожидает проверки

#158 Kashitsyna N.A. lab2
  ISTbd-21/KashitsynaNA/lab2/Source.cpp
  ISTbd-21/KashitsynaNA/lab2/Отчет.md
Labels: ИСТбд-21, Принято

#132 Osipov-K-S-lab-1-2
  ISTbd-22/Осипов К.С/lab1/README.md
  ISTbd-22/Осипов К.С/lab1/README2.md
  ISTbd-22/Осипов К.С/lab1/main.cpp
  ИСТбд-22/Осипов К.С/lab1/README.md
  ИСТбд-22/Осипов К.С/lab1/main.cpp
  ИСТбд-22/Осипов К.С/lab2/Отчёт лаб2.md
Labels: ИСТбд-22, Ожидает проверки

#133 Osipov-K-S-lab-3
  ISTbd-22/Осипов К.С/lab3/README.md
  ISTbd-22/Осипов К.С/lab3/main.cpp
  ИСТбд-22/Осипов К.С/lab3/README.md
  ИСТбд-22/Осипов К.С/lab3/main.cpp
Labels: ИСТбд-22, Ожидает проверки

#137 Osipov-K-S-lab-6
  ISTbd-22/Осипов К.С/lab6/README.md
  ISTbd-22/Осипов К.С/lab6/main.cpp
  ИСТбд-22/Осипов К.С/lab6/README.md
  ИСТбд-22/Осипов К.С/lab6/main.cpp
Labels: ИСТбд-22, Принято

#160 Osipov-K-S-lab-7
  ISTbd-22/Осипов К.С/lab7/README.md
  ISTbd-22/Осипов К.С/lab7/main.cpp
Labels: ИСТбд-22, Ожидает проверки

#148 Кучина А. А. Лабораторная работа№3
  ISTbd-22/Kuchina A. A/lab3/Source.cpp
  ISTbd-22/Kuchina A. A/lab3/Отчет.md
Labels: ИСТбд-22, Принято

#151 Ushkova A. S. lab7
  ISTbd-22/Ushkova A. S/lab7/hanoi.cpp
  ISTbd-22/Ushkova A. S/lab7/отчет.md
Labels: ИСТбд-22, Принято

#157 Iskhakov T. I. lab 3
  ISTbd-22/Iskhakov T. I/lab3/main.cpp
  ISTbd-22/Iskhakov T. I/lab3/report.md
Labels: ИСТбд-22, Принято

#167 Iskhakov T I lab 4
  ISTbd-22/Iskhakov T. I/lab4/main.cpp
  ISTbd-22/Iskhakov T. I/lab4/report.md
Labels: ИСТбд-22, Принято

#152 Kashitsyna N. A. lab1
  ISTbd-21/KashitsynaNA/lab1/Source.cpp
  ISTbd-21/KashitsynaNA/lab1/Отчет.md
Labels: ИСТбд-21, Принято

#156 Loginov N V lab 8.1
  ISTbd-21/LoginovNV/lab8.1/Element.h
  ISTbd-21/LoginovNV/lab8.1/Report.md
  ISTbd-21/LoginovNV/lab8.1/Turn.cpp
  ISTbd-21/LoginovNV/lab8.1/Turn.h
  ISTbd-21/LoginovNV/lab8.1/lab8.1.cpp
Labels: ИСТбд-21, Принято

#159 Бакунькина Н. М. Лаба 4
  ISTbd-21/BakunkinaNM/lab4/main.cpp
  ISTbd-21/BakunkinaNM/lab4/report.md
Labels: ИСТбд-21, Принято

#163 Gilmetdinova add lab 3
  ISTbd-21/GilmetdinovaED/lab-3/lab-3.cbp
  ISTbd-21/GilmetdinovaED/lab-3/lab-3.depend
  ISTbd-21/GilmetdinovaED/lab-3/lab-3.layout
  ISTbd-21/GilmetdinovaED/lab-3/main.cpp
  ISTbd-21/GilmetdinovaED/lab-3/report.md
Labels: ИСТбд-21, Принято

#168 add lab 6
  ISTbd-21/Ulianin A. A/lab6/lab6_1.cpp
  ISTbd-21/Ulianin A. A/lab6/lab6_2.cpp
  ISTbd-21/Ulianin A. A/lab6/lab6_3.cpp
  ISTbd-21/Ulianin A. A/lab6/readMe.md
Labels: ИСТбд-21, Принято

#169 add lab 7
  ISTbd-21/Ulianin A. A/lab7/lab7.cpp
  ISTbd-21/Ulianin A. A/lab7/readMe.md
Labels: ИСТбд-21, Принято

#170 Грязнов Е. лаб 0
  ISTbd-21/Gryaznov E.A/lab 0/lab 0.cpp
  ISTbd-21/Gryaznov E.A/lab 0/readMe.md
Labels: ИСТбд-21, Принято

#136 Uskova A S lab5
  ISTbd-22/Ushkova A. S/lab5/Simple_Merging_Sort.cpp
  ISTbd-22/Ushkova A. S/lab5/text.txt
  ISTbd-22/Ushkova A. S/lab5/отчет.md
Labels: ИСТбд-22, Принято

#165 Тагашев Иван - Лаб №6
  ISTbd-22/Tagashev I.I/lab6/Source.cpp
  ISTbd-22/Tagashev I.I/lab6/Source1.cpp
  ISTbd-22/Tagashev I.I/lab6/Source2.cpp
  ISTbd-22/Tagashev I.I/lab6/отчёт.md
Labels: ИСТбд-22, Принято

#166 Тагашев Иван - Lab7
  ISTbd-22/Tagashev I.I/lab7/Source.cpp
  ISTbd-22/Tagashev I.I/lab7/отчёт.md
Labels: ИСТбд-22, Принято

#171 Саушкина Н. С. лаб. 5
  ISTbd-22/Saushkina_N_S/lab5/main.cpp
  ISTbd-22/Saushkina_N_S/lab5/myFile.txt
  ISTbd-22/Saushkina_N_S/lab5/report.md
  ISTbd-22/Saushkina_N_S/lab5/smsort_1.txt
  ISTbd-22/Saushkina_N_S/lab5/smsort_2.txt
Labels: ИСТбд-22, Принято

#175 Саушкина Н. С. лаб. 6
  ISTbd-22/Saushkina_N_S/lab6/main1.cpp
  ISTbd-22/Saushkina_N_S/lab6/main2.cpp
  ISTbd-22/Saushkina_N_S/lab6/main3.cpp
  ISTbd-22/Saushkina_N_S/lab6/report.md
Labels: ИСТбд-22, Принято

#180 Саушкина Н. С. лаб. 7
  ISTbd-22/Saushkina_N_S/lab7/main.cpp
  ISTbd-22/Saushkina_N_S/lab7/report.md
Labels: ИСТбд-22, Принято

#185 Саушкина Н. С. лаб. 8.1
  ISTbd-22/Saushkina_N_S/lab8.1/main.cpp
  ISTbd-22/Saushkina_N_S/lab8.1/report.md
Labels: ИСТбд-22, Принято

#172 Iskhakov E A, lab4
  ISTbd-22/Iskhakov E A/lab4/main.cpp
  ISTbd-22/Iskhakov E A/lab4/otchet.md
Labels: ИСТбд-22, Принято

#182 Osipov-K-S-lab-4
  ISTbd-22/Осипов К.С/lab4/README.md
  ISTbd-22/Осипов К.С/lab4/main.cpp
Labels: ИСТбд-22, Принято

#187 [Hodarev-D-A] Added lab5.
  ISTbd-22/Ходарев Д.А/lab1/README.md
  ISTbd-22/Ходарев Д.А/lab1/lab1.cpp
  ISTbd-22/Ходарев Д.А/lab2/README.md
  ISTbd-22/Ходарев Д.А/lab2/lab2.cpp
  ISTbd-22/Ходарев Д.А/lab3/README.md
  ISTbd-22/Ходарев Д.А/lab3/lab3.cpp
  ISTbd-22/Ходарев Д.А/lab4/README.md
  ISTbd-22/Ходарев Д.А/lab4/lab4.cpp
  ISTbd-22/Ходарев Д.А/lab5/README.md
  ISTbd-22/Ходарев Д.А/lab5/lab5.sln
  ISTbd-22/Ходарев Д.А/lab5/lab5/Arr1.txt
  ISTbd-22/Ходарев Д.А/lab5/lab5/Arr2.txt
  ISTbd-22/Ходарев Д.А/lab5/lab5/Array.txt
  ISTbd-22/Ходарев Д.А/lab5/lab5/lab5.cpp
  ISTbd-22/Ходарев Д.А/lab5/lab5/lab5.vcxproj
  ISTbd-22/Ходарев Д.А/lab5/lab5/lab5.vcxproj.filters
  ISTbd-22/Ходарев Д.А/lab5/lab5/lab5.vcxproj.user
  ISTbd-22/Ходарев Д.А/lab6/README.md
  ISTbd-22/Ходарев Д.А/lab6/lab6.cpp
  ISTbd-22/Ходарев Д.А/lab7/README.md
  ISTbd-22/Ходарев Д.А/lab7/lab7.cpp
Labels: ИСТбд-22, Принято

#188 чистить чистить раз раз раз
  ISTbd-22/Iskhakov E A/lab3/Source.cpp
  ISTbd-22/Iskhakov E A/lab3/untitled.md
  ISTbd-22/Осипов К.С/lab1/main.cpp
  ISTbd-22/Осипов К.С/lab2/Отчёт лаб2.md
  ИСТбд-22/Осипов К.С/lab1/README.md
  ИСТбд-22/Осипов К.С/lab1/main.cpp
  ИСТбд-22/Осипов К.С/lab3/README.md
  ИСТбд-22/Осипов К.С/lab3/main.cpp
  ИСТбд-22/Осипов К.С/lab6/README.md
  ИСТбд-22/Осипов К.С/lab6/main.cpp
Labels: Не по делу

#173 EgorovIE_lab3
  ISTbd-22/Egorov I.E/lab3/lab3.cpp
  ISTbd-22/Egorov I.E/lab3/lab3.md
  ИСТбд-22/Егоров И.Е/lab0/Untitled-1.cpp
  ИСТбд-22/Егоров И.Е/lab0/ОтчётЛаба0.md
Labels: ИСТбд-22, На доработку, Принято

#189 Return labs
  ISTbd-22/Egorov I.E/lab0/Untitled-1.cpp
  ISTbd-22/Egorov I.E/lab0/ОтчётЛаба0.md
  ISTbd-22/Egorov I.E/lab1/README.md
  ISTbd-22/Egorov I.E/lab1/main.cpp
Labels: Не по делу
