Repository Qui-Gon173/AiSD-2020, pull requests merged in 2020-12, with the labels that each got.

#176 Бакунькина Н. М. Лаба 5
  ISTbd-21/BakunkinaNM/lab5/main.cpp
  ISTbd-21/BakunkinaNM/lab5/report.md
Labels: ИСТбд-21, Принято

#177 Бакунькина Н. М. Лаба 6
  ISTbd-21/BakunkinaNM/lab6/example1.cpp
  ISTbd-21/BakunkinaNM/lab6/example2.cpp
  ISTbd-21/BakunkinaNM/lab6/example3.cpp
  ISTbd-21/BakunkinaNM/lab6/report.md
Labels: ИСТбд-21, Принято

#178 Бакунькина Н. М. Лаба 7
  ISTbd-21/BakunkinaNM/lab7/main.cpp
  ISTbd-21/BakunkinaNM/lab7/report.md
Labels: ИСТбд-21, Принято

#183 Petrova A.A., add lab4
  ISTbd-21/PetrovaAA/lab4/main.cpp
  ISTbd-21/PetrovaAA/lab4/report4.md
Labels: ИСТбд-21, Принято

#184 Kartashova M.V add lab 4
  ISTbd-21/Kartashova M.V/lab-4/lab-4.cpp
  ISTbd-21/Kartashova M.V/lab-4/report4.md
Labels: ИСТбд-21, Принято

#190 Kashitsyna N.A. lab3
  ISTbd-21/KashitsynaNA/lab3/Source.cpp
  ISTbd-21/KashitsynaNA/lab3/Отчет.md
Labels: ИСТбд-21, Принято

#195 Gilmetdinova add lab 5
  ISTbd-21/GilmetdinovaED/lab-5/File.txt
  ISTbd-21/GilmetdinovaED/lab-5/lab-5.cbp
  ISTbd-21/GilmetdinovaED/lab-5/lab-5.depend
  ISTbd-21/GilmetdinovaED/lab-5/lab-5.layout
  ISTbd-21/GilmetdinovaED/lab-5/main.cpp
  ISTbd-21/GilmetdinovaED/lab-5/report.md
Labels: ИСТбд-21, Принято

#196 Loginov N V lab 8.2
  ISTbd-21/LoginovNV/lab8.2/ArifmGenerator.cpp
  ISTbd-21/LoginovNV/lab8.2/ArifmGenerator.h
  ISTbd-21/LoginovNV/lab8.2/ArifmIter.cpp
  ISTbd-21/LoginovNV/lab8.2/ArifmIter.h
  ISTbd-21/LoginovNV/lab8.2/Element.h
  ISTbd-21/LoginovNV/lab8.2/Report.md
  ISTbd-21/LoginovNV/lab8.2/Turn.cpp
  ISTbd-21/LoginovNV/lab8.2/Turn.h
  ISTbd-21/LoginovNV/lab8.2/TurnIterator.cpp
  ISTbd-21/LoginovNV/lab8.2/TurnIterator.h
  ISTbd-21/LoginovNV/lab8.2/lab8.2.cpp
Labels: ИСТбд-21, Принято

#201 Kartashova M lab 5
  ISTbd-21/Kartashova M.V/lab-5/chisla.txt
  ISTbd-21/Kartashova M.V/lab-5/lab-5.cpp
  ISTbd-21/Kartashova M.V/lab-5/report5.md
Labels: ИСТбд-21, Принято

#202 Petrova A.A., add lab6
  ISTbd-21/PetrovaAA/lab6/main6.1.cpp
  ISTbd-21/PetrovaAA/lab6/main6.2.cpp
  ISTbd-21/PetrovaAA/lab6/main6.3.cpp
  ISTbd-21/PetrovaAA/lab6/report6.md
Labels: ИСТбд-21, Принято

#203 Грязнов Е.А. лаб 3
  ISTbd-21/Gryaznov E.A/lab 3/lab 3.cpp
  ISTbd-21/Gryaznov E.A/lab 3/lab 3.md
Labels: ИСТбд-21, Принято

#204 Petrova A.A., add lab 7
  ISTbd-21/PetrovaAA/lab7/main.cpp
  ISTbd-21/PetrovaAA/lab7/report7.md
Labels: ИСТбд-21, Принято

#206 Крахмалюк Д.А. лаб0
  ISTbd-22/Krakhmalyuk-D-A/lab0/aisd_lab0.cpp
  ISTbd-22/Krakhmalyuk-D-A/lab0/readme.md
Labels: ИСТбд-22, Ожидает проверки

#162 Doronkin A N lab 3
  ISTbd-22/Doronkin A.N/lab3/main.cpp
  ISTbd-22/Doronkin A.N/lab3/Отчет.md
Labels: ИСТбд-22, Ожидает проверки

#193 Ushkova A. S. lab8.1
  ISTbd-22/Ushkova A. S/lab8.1/spisok.cpp
  ISTbd-22/Ushkova A. S/lab8.1/отчет.md
Labels: ИСТбд-22, Принято

#194 Osipov-K-S-lab-5
  ISTbd-22/Осипов К.С/lab5/README.md
  ISTbd-22/Осипов К.С/lab5/array.txt
  ISTbd-22/Осипов К.С/lab5/main.cpp
  ISTbd-22/Осипов К.С/lab5/unsorted.txt
Labels: ИСТбд-22, Принято

#191 Грязнов Е. лаб 1
  ISTbd-21/Gryaznov E.A/lab 1/lab 1.cpp
  ISTbd-21/Gryaznov E.A/lab 1/lab 1.md
Labels: ИСТбд-21, Принято

#192 Грязнов Е. лаб 2
  ISTbd-21/Gryaznov E.A/lab 2/lab 2.cpp
  ISTbd-21/Gryaznov E.A/lab 2/lab 2.md
Labels: ИСТбд-21, Принято

#205 Gilmetdinova add lab 6
  ISTbd-21/GilmetdinovaED/lab-6/main1.cpp
  ISTbd-21/GilmetdinovaED/lab-6/main2.cpp
  ISTbd-21/GilmetdinovaED/lab-6/main3.cpp
  ISTbd-21/GilmetdinovaED/lab-6/report.md
Labels: ИСТбд-21, Принято

#207 add lab 8-1
  ISTbd-21/Ulianin A. A/lab8-1/lab8-1.cpp
  ISTbd-21/Ulianin A. A/lab8-1/readMe.md
Labels: ИСТбд-21, Принято

#215 Грязнов Е. лаб 4
  ISTbd-21/Gryaznov E.A/lab 4/lab 4.cpp
  ISTbd-21/Gryaznov E.A/lab 4/lab 4.md
Labels: ИСТбд-21, Принято

#208 Enilov-D-A-lab-8.2
  ISTbd-22/Енилов Д.А/lab3/main.cpp
  ISTbd-22/Енилов Д.А/lab8.2/List.h
  ISTbd-22/Енилов Д.А/lab8.2/Node.cpp
  ISTbd-22/Енилов Д.А/lab8.2/main.cpp
  ISTbd-22/Енилов Д.А/lab8.2/my_geo_generator.cpp
  ISTbd-22/Енилов Д.А/lab8.2/my_iterator.cpp
  ISTbd-22/Енилов Д.А/lab8.2/отчет.md
Labels: ИСТбд-22, Принято

#209 no message
  ISTbd-22/Kuchina A. A/lab4/Source.cpp
  ISTbd-22/Kuchina A. A/lab4/Отчет.md
Labels: ИСТбд-22, Ожидает проверки

#210 Sedykh-N-V-lab-0
  ISTbd-22/Sedykh N. V/lab0/main.cpp
  ISTbd-22/Sedykh N. V/lab0/отчет.md
Labels: ИСТбд-22, Ожидает проверки

#212 Sedykh-N-V-lab-1
  ISTbd-22/Sedykh N. V/lab1/lab1.cpp
  ISTbd-22/Sedykh N. V/lab1/отчет.md
Labels: ИСТбд-22, Ожидает проверки

#213 Крахмалюк Д.А. лаба 1
  ISTbd-22/Krakhmalyuk-D-A/lab1/aisd_lab1.cpp
  ISTbd-22/Krakhmalyuk-D-A/lab1/readme.md
Labels: ИСТбд-22, Ожидает проверки

#219 Крахмалюк Д.А. лаба 3
  ISTbd-22/Krakhmalyuk-D-A/lab3/aisd_lab3.cpp
  ISTbd-22/Krakhmalyuk-D-A/lab3/readme.md
Labels: ИСТбд-22, На доработку

#197 [HODAREV-D-A] Added lab 8.1
  ISTbd-22/Ходарев Д.А/lab1/README.md
  ISTbd-22/Ходарев Д.А/lab1/lab1.cpp
  ISTbd-22/Ходарев Д.А/lab2/README.md
  ISTbd-22/Ходарев Д.А/lab2/lab2.cpp
  ISTbd-22/Ходарев Д.А/lab3/README.md
  ISTbd-22/Ходарев Д.А/lab3/lab3.cpp
  ISTbd-22/Ходарев Д.А/lab4/README.md
  ISTbd-22/Ходарев Д.А/lab4/lab4.cpp
  ISTbd-22/Ходарев Д.А/lab5/README.md
  ISTbd-22/Ходарев Д.А/lab5/lab5.sln
  ISTbd-22/Ходарев Д.А/lab5/lab5/Arr1.txt
  ISTbd-22/Ходарев Д.А/lab5/lab5/Arr2.txt
  ISTbd-22/Ходарев Д.А/lab5/lab5/Array.txt
  ISTbd-22/Ходарев Д.А/lab5/lab5/lab5.cpp
  ISTbd-22/Ходарев Д.А/lab5/lab5/lab5.vcxproj
  ISTbd-22/Ходарев Д.А/lab5/lab5/lab5.vcxproj.filters
  ISTbd-22/Ходарев Д.А/lab5/lab5/lab5.vcxproj.user
  ISTbd-22/Ходарев Д.А/lab6/README.md
  ISTbd-22/Ходарев Д.А/lab6/lab6.cpp
  ISTbd-22/Ходарев Д.А/lab7/README.md
  ISTbd-22/Ходарев Д.А/lab7/lab7.cpp
  ISTbd-22/Ходарев Д.А/lab8.1/README.md
  ISTbd-22/Ходарев Д.А/lab8.1/Vector.h
  ISTbd-22/Ходарев Д.А/lab8.1/lab8.1.cpp
Labels: ИСТбд-22, На доработку

#164 Тагашев Иван - Lab-5
  ISTbd-22/Tagashev I.I/lab5/lab5/file.txt
  ISTbd-22/Tagashev I.I/lab5/lab5/lab5.cpp
  ISTbd-22/Tagashev I.I/lab5/lab5/lab5.sln
  ISTbd-22/Tagashev I.I/lab5/lab5/lab5.vcxproj
  ISTbd-22/Tagashev I.I/lab5/lab5/lab5.vcxproj.filters
  ISTbd-22/Tagashev I.I/lab5/lab5/lab5.vcxproj.user
  ISTbd-22/Tagashev I.I/lab5/lab5/smsort_1.txt
  ISTbd-22/Tagashev I.I/lab5/lab5/smsort_2.txt
  ISTbd-22/Tagashev I.I/lab5/laba__5.sln
  ISTbd-22/Tagashev I.I/lab5/laba__5/Source.cpp
  ISTbd-22/Tagashev I.I/lab5/laba__5/input.txt
  ISTbd-22/Tagashev I.I/lab5/laba__5/laba__5.vcxproj
  ISTbd-22/Tagashev I.I/lab5/laba__5/laba__5.vcxproj.filters
  ISTbd-22/Tagashev I.I/lab5/laba__5/laba__5.vcxproj.user
  ISTbd-22/Tagashev I.I/lab5/laba__5/output.txt
  ISTbd-22/Tagashev I.I/lab5/laba__5/test.txt
  ISTbd-22/Tagashev I.I/lab5/main.cpp
  ISTbd-22/Tagashev I.I/lab5/отчёт.md
Labels: ИСТбд-22, Принято

#220 Крахмалюк Д.А. Лаб4
  ISTbd-22/Krakhmalyuk-D-A/lab4/aisd_lab4.cpp
  ISTbd-22/Krakhmalyuk-D-A/lab4/readme.md
Labels: ИСТбд-22, Ожидает проверки

#222 Седых Н.В. lab2
  ISTbd-22/Sedykh N. V/lab2/lab2.cpp
  ISTbd-22/Sedykh N. V/lab2/отчет.md
Labels: ИСТбд-22, Принято

#223 Sedykh-N-V-lab-3
  ISTbd-22/Sedykh N. V/lab3/lab3.cpp
  ISTbd-22/Sedykh N. V/lab3/отчет.md
Labels: ИСТбд-22, Принято

#224 Sedykh-N-V-lab-4
  ISTbd-22/Sedykh N. V/lab4/lab4.cpp
  ISTbd-22/Sedykh N. V/lab4/отчет.md
Labels: ИСТбд-22, Ожидает проверки

#225 Sedykh-N-V-lab-5
  ISTbd-22/Sedykh N. V/lab5/lab5.cpp
  ISTbd-22/Sedykh N. V/lab5/text.txt
  ISTbd-22/Sedykh N. V/lab5/отчет.md
Labels: ИСТбд-22, Принято

#226 Sedykh-N-V-lab-6
  ISTbd-22/Sedykh N. V/lab6/lab6.cpp
  ISTbd-22/Sedykh N. V/lab6/lab6_2.cpp
  ISTbd-22/Sedykh N. V/lab6/lab6_3.cpp
  ISTbd-22/Sedykh N. V/lab6/отчет.md
Labels: ИСТбд-22, Принято

#227 Sedykh-N-V-lab-7
  ISTbd-22/Sedykh N. V/lab7/lab7.cpp
  ISTbd-22/Sedykh N. V/lab7/отчет.md
Labels: ИСТбд-22, Ожидает проверки

#231 [Hodarev-D-A] Fix lab8.1
  ISTbd-22/Ходарев Д.А/lab1/README.md
  ISTbd-22/Ходарев Д.А/lab1/lab1.cpp
  ISTbd-22/Ходарев Д.А/lab2/README.md
  ISTbd-22/Ходарев Д.А/lab2/lab2.cpp
  ISTbd-22/Ходарев Д.А/lab3/README.md
  ISTbd-22/Ходарев Д.А/lab3/lab3.cpp
  ISTbd-22/Ходарев Д.А/lab4/README.md
  ISTbd-22/Ходарев Д.А/lab4/lab4.cpp
  ISTbd-22/Ходарев Д.А/lab5/README.md
  ISTbd-22/Ходарев Д.А/lab5/lab5.sln
  ISTbd-22/Ходарев Д.А/lab5/lab5/Arr1.txt
  ISTbd-22/Ходарев Д.А/lab5/lab5/Arr2.txt
  ISTbd-22/Ходарев Д.А/lab5/lab5/Array.txt
  ISTbd-22/Ходарев Д.А/lab5/lab5/lab5.cpp
  ISTbd-22/Ходарев Д.А/lab5/lab5/lab5.vcxproj
  ISTbd-22/Ходарев Д.А/lab5/lab5/lab5.vcxproj.filters
  ISTbd-22/Ходарев Д.А/lab5/lab5/lab5.vcxproj.user
  ISTbd-22/Ходарев Д.А/lab6/README.md
  ISTbd-22/Ходарев Д.А/lab6/lab6.cpp
  ISTbd-22/Ходарев Д.А/lab7/README.md
  ISTbd-22/Ходарев Д.А/lab7/lab7.cpp
  ISTbd-22/Ходарев Д.А/lab8.1/README.md
  ISTbd-22/Ходарев Д.А/lab8.1/Vector.h
  ISTbd-22/Ходарев Д.А/lab8.1/lab8.1.cpp
Labels: ИСТбд-22, Принято

#237 [Hodarev-D-A] Added lab8.2
  ISTbd-22/Ходарев Д.А/lab8.2/Generator.h
  ISTbd-22/Ходарев Д.А/lab8.2/Math.h
  ISTbd-22/Ходарев Д.А/lab8.2/Print.h
  ISTbd-22/Ходарев Д.А/lab8.2/README.md
  ISTbd-22/Ходарев Д.А/lab8.2/Vector.h
  ISTbd-22/Ходарев Д.А/lab8.2/VectorIter.h
  ISTbd-22/Ходарев Д.А/lab8.2/lab8.2.cpp
Labels: ИСТбд-22, Ожидает проверки

#238 6 лабораторная работа. 5-я в процессе
  ISTbd-22/Kuchina A. A/lab6/main1.cpp
  ISTbd-22/Kuchina A. A/lab6/main2.cpp
  ISTbd-22/Kuchina A. A/lab6/main3.cpp
  ISTbd-22/Kuchina A. A/lab6/отчет.md
Labels: ИСТбд-22, Принято

#240 no message
  ISTbd-22/Kuchina A. A/lab7/main.cpp
  ISTbd-22/Kuchina A. A/lab7/Отчет.md
Labels: ИСТбд-22, Ожидает проверки

#216 Грязнов Е. лаб 5
  ISTbd-21/Gryaznov E.A/lab 5/LAB5.cpp
  ISTbd-21/Gryaznov E.A/lab 5/lab 5.md
  ISTbd-21/Gryaznov E.A/lab 5/sort.txt
Labels: ИСТбд-21, Принято

#217 Грязнов Е. лаб 6
  ISTbd-21/Gryaznov E.A/lab 6/lab 6.md
  ISTbd-21/Gryaznov E.A/lab 6/lab6.1.cpp
  ISTbd-21/Gryaznov E.A/lab 6/lab6.2.cpp
  ISTbd-21/Gryaznov E.A/lab 6/lab6.3.cpp
Labels: ИСТбд-21, Принято

#247 Миридонов П.А lab 0
  ISTbd-22/Miridonov-P-A/lab0/main.cpp
  ISTbd-22/Miridonov-P-A/lab0/Отчет.md
Labels: ИСТбд-22, Принято

#244 Крахмалюк Д.А. лаб 6
  ISTbd-22/Krakhmalyuk-D-A/lab5/aisd_lab5.cpp
  ISTbd-22/Krakhmalyuk-D-A/lab5/readme.md
  ISTbd-22/Krakhmalyuk-D-A/lab6/1.cpp
  ISTbd-22/Krakhmalyuk-D-A/lab6/2.cpp
  ISTbd-22/Krakhmalyuk-D-A/lab6/3.cpp
  ISTbd-22/Krakhmalyuk-D-A/lab6/readme.md
Labels: ИСТбд-22, Ожидает проверки

#239 Крахмалюк Д.А. лаб 5
  ISTbd-22/Krakhmalyuk-D-A/lab5/aisd_lab5.cpp
  ISTbd-22/Krakhmalyuk-D-A/lab5/readme.md
Labels: ИСТбд-22, На доработку

#245 Крахмалюк Д.А. лаб 7
  ISTbd-22/Krakhmalyuk-D-A/lab6/readme.md
  ISTbd-22/Krakhmalyuk-D-A/lab7/aisd_lab7.cpp
  ISTbd-22/Krakhmalyuk-D-A/lab7/readme.md
Labels: ИСТбд-22, Принято

#218 Gilmetdinova add lab 7
  ISTbd-21/GilmetdinovaED/lab-7/main.cpp
  ISTbd-21/GilmetdinovaED/lab-7/report.md
Labels: ИСТбд-21, Ожидает проверки

#221 Kashitsyna N. A. lab4
  ISTbd-21/KashitsynaNA/lab4/Source.cpp
  ISTbd-21/KashitsynaNA/lab4/Отчет.md
Labels: ИСТбд-21, Принято

#228 Грязнов Е. лаб 7
  ISTbd-21/Gryaznov E.A/lab 7/lab 7.cpp
  ISTbd-21/Gryaznov E.A/lab 7/lab 7.md
Labels: ИСТбд-21, Принято

#233 Бакунькина Н. М. Лаба 8.1
  ISTbd-21/BakunkinaNM/lab8.1/Node.h
  ISTbd-21/BakunkinaNM/lab8.1/Stack.h
  ISTbd-21/BakunkinaNM/lab8.1/main.cpp
  ISTbd-21/BakunkinaNM/lab8.1/report.md
Labels: ИСТбд-21, Принято

#234 Бакунькина Н. М. Лаба 8.2
  ISTbd-21/BakunkinaNM/lab8.2/FibGenerator.h
  ISTbd-21/BakunkinaNM/lab8.2/Node.h
  ISTbd-21/BakunkinaNM/lab8.2/Stack.h
  ISTbd-21/BakunkinaNM/lab8.2/StackIterator.h
  ISTbd-21/BakunkinaNM/lab8.2/main.cpp
  ISTbd-21/BakunkinaNM/lab8.2/report.md
Labels: ИСТбд-21, Принято

#241 Gilmetdinova add lab 8.1
  ISTbd-21/GilmetdinovaED/lab-8.1/main.cpp
  ISTbd-21/GilmetdinovaED/lab-8.1/report.md
Labels: ИСТбд-21, Принято

#242 Kartashova add lab6
  ISTbd-21/Kartashova M.V/lab-6/lab-6.1.cpp
  ISTbd-21/Kartashova M.V/lab-6/lab-6.2.cpp
  ISTbd-21/Kartashova M.V/lab-6/lab-6.3.cpp
  ISTbd-21/Kartashova M.V/lab-6/report6.md
Labels: ИСТбд-21, Принято

#243 Create KupriyanovDD
  ISTbd-21/KupriyanovDD
Labels: ИСТбд-21, Принято

#246 Kartashova M add lab7
  ISTbd-21/Kartashova M.V/lab-7/lab-7.cpp
  ISTbd-21/Kartashova M.V/lab-7/report7.md
Labels: ИСТбд-21, Принято

#200 Alekseenko d v lab 4
  ISTbd-21/AlekseenkoDV/lab3/main.cpp
  ISTbd-21/AlekseenkoDV/lab3/readme.md
  ISTbd-21/AlekseenkoDV/lab4/SortTree.png
  ISTbd-21/AlekseenkoDV/lab4/main.cpp
  ISTbd-21/AlekseenkoDV/lab4/report.md
Labels: ИСТбд-21, Принято

#199 Alekseenko d v lab 3
  ISTbd-21/AlekseenkoDV/lab3/main.cpp
  ISTbd-21/AlekseenkoDV/lab3/readme.md
Labels: ИСТбд-21, На доработку

#235 EgorovIE-lab5(fix)
  ISTbd-22/Egorov I.E/lab5/lab5.cpp
  ISTbd-22/Egorov I.E/lab5/lab5.md
Labels: ИСТбд-22, Ожидает проверки

#248 Гурьянов Алексей Вячеславович, Лаб 8.1
  ISTbd-22/Гурьянов А.В/lab8.1/main.cpp
  ISTbd-22/Гурьянов А.В/lab8.1/readme.md
Labels: ИСТбд-22, Принято

#251 Лаба 2 вар 4
  ISTbd-22/Miridonov-P-A/lab2/main.cpp
  ISTbd-22/Miridonov-P-A/lab2/Отчет.md
Labels: ИСТбд-22, Принято

#252 Миридонов П.А Лаба №3
  ISTbd-22/Miridonov-P-A/lab3/main.cpp
  ISTbd-22/Miridonov-P-A/lab3/Отчет.md
Labels: ИСТбд-22, Принято

#255 Миридонов П.А лаба 4
  ISTbd-22/Miridonov-P-A/lab4/main.cpp
  ISTbd-22/Miridonov-P-A/lab4/Отчет.md
Labels: ИСТбд-22, Принято

#263 Миридонов Павел Лаба 7
  ISTbd-22/Miridonov-P-A/lab7/lab7.cpp
  ISTbd-22/Miridonov-P-A/lab7/Отчет.md
Labels: ИСТбд-22, Ожидает проверки

#262 Миридонов Павел Лаба 6
  ISTbd-22/Miridonov-P-A/lab6/Lab6.1.cpp
  ISTbd-22/Miridonov-P-A/lab6/Lab6.2.cpp
  ISTbd-22/Miridonov-P-A/lab6/Lab6.3.cpp
  ISTbd-22/Miridonov-P-A/lab6/Отчет.md
Labels: ИСТбд-22, Принято

#249 Миридонов П.А Лабораторная работа 1
  ISTbd-22/Miridonov-P-A/lab1/main.cpp
  ISTbd-22/Miridonov-P-A/lab1/Отчет.md
Labels: ИСТбд-22, Ожидает проверки

#269 Kuchina-A-A-lab5
  ISTbd-22/Kuchina A. A/lab5/main.cpp
  ISTbd-22/Kuchina A. A/lab5/Отчет.md
Labels: ИСТбд-22, Принято

#256 Iskhakov T I lab 5
  ISTbd-22/Iskhakov T. I/lab5/file.txt
  ISTbd-22/Iskhakov T. I/lab5/main.cpp
  ISTbd-22/Iskhakov T. I/lab5/report.md
Labels: ИСТбд-22, Принято

#260 Iskhakov T I lab 6
  ISTbd-22/Iskhakov T. I/lab6/main1.cpp
  ISTbd-22/Iskhakov T. I/lab6/main2.cpp
  ISTbd-22/Iskhakov T. I/lab6/main3.cpp
  ISTbd-22/Iskhakov T. I/lab6/report.md
Labels: ИСТбд-22, Принято

#270 Iskhakov T I lab 7
  ISTbd-22/Iskhakov T. I/lab7/main.cpp
  ISTbd-22/Iskhakov T. I/lab7/report.md
Labels: ИСТбд-22, Ожидает проверки

#253 Doronkin.A.N Lab 4
  ISTbd-22/Doronkin A.N/lab4/main.cpp
  ISTbd-22/Doronkin A.N/lab4/Отчет.md
Labels: ИСТбд-22, Ожидает проверки

#271 Doronkin.A.N lab6
  ISTbd-22/Doronkin A.N/lab6/Lab6_1.cpp
  ISTbd-22/Doronkin A.N/lab6/Lab6_2.cpp
  ISTbd-22/Doronkin A.N/lab6/Lab6_3.cpp
  ISTbd-22/Doronkin A.N/lab6/Отчет.md
Labels: ИСТбд-22, Ожидает проверки

#264 Iskhakov-E-A-lab5
  ISTbd-22/Iskhakov E A/lab5/Source.cpp
  ISTbd-22/Iskhakov E A/lab5/file.txt
  ISTbd-22/Iskhakov E A/lab5/report.md
Labels: ИСТбд-22, Ожидает проверки

#265 Iskhakov-E-A-lab6.
  ISTbd-22/Iskhakov E A/lab6/Source.cpp
  ISTbd-22/Iskhakov E A/lab6/Source1.cpp
  ISTbd-22/Iskhakov E A/lab6/Source2.cpp
  ISTbd-22/Iskhakov E A/lab6/отчёт.md
Labels: ИСТбд-22, Принято

#266 Iskhakov-E-A-lab7
  ISTbd-22/Iskhakov E A/lab7/Source.cpp
  ISTbd-22/Iskhakov E A/lab7/отчёт.md
Labels: ИСТбд-22, Принято

#274 Саушкина Н. С. лаб. 8.2
  ISTbd-22/Saushkina_N_S/lab8.2/List.h
  ISTbd-22/Saushkina_N_S/lab8.2/Node.cpp
  ISTbd-22/Saushkina_N_S/lab8.2/fibonacci_numbers_generator.cpp
  ISTbd-22/Saushkina_N_S/lab8.2/iterator.cpp
  ISTbd-22/Saushkina_N_S/lab8.2/main.cpp
  ISTbd-22/Saushkina_N_S/lab8.2/pic1.png
  ISTbd-22/Saushkina_N_S/lab8.2/report.md
Labels: ИСТбд-22, Принято

#236 Тагашев И.И. - lab-8.1
  ISTbd-22/Tagashev I.I/lab8.1/list.h
  ISTbd-22/Tagashev I.I/lab8.1/readme.md
  ISTbd-22/Tagashev I.I/lab8.1/source.cpp
Labels: ИСТбд-22, Ожидает проверки

#276 Doronkin.A.N lab 7
  ISTbd-22/Doronkin A.N/lab7/main.cpp
  ISTbd-22/Doronkin A.N/lab7/Отчет.md
Labels: ИСТбд-22, Ожидает проверки

#273 Doronkin.A.N lab 5
  ISTbd-22/Doronkin A.N/lab5/Laba_5_ver2.cbp
  ISTbd-22/Doronkin A.N/lab5/Laba_5_ver2.depend
  ISTbd-22/Doronkin A.N/lab5/Laba_5_ver2.layout
  ISTbd-22/Doronkin A.N/lab5/main.cpp
  ISTbd-22/Doronkin A.N/lab5/mass.txt
  ISTbd-22/Doronkin A.N/lab5/Отчет.md
Labels: ИСТбд-22, Ожидает проверки

#268 Kuchina-A-A-lab8.1
  ISTbd-22/Kuchina A. A/lab8.1/list.h
  ISTbd-22/Kuchina A. A/lab8.1/main.cpp
  ISTbd-22/Kuchina A. A/lab8.1/отчет.md
Labels: ИСТбд-22, Принято

#275 Миридонов Павел lab5
  ISTbd-22/Miridonov-P-A/lab5/AllArray.txt
  ISTbd-22/Miridonov-P-A/lab5/lab5.cpp
  ISTbd-22/Miridonov-P-A/lab5/Отчет.md
Labels: ИСТбд-22, Принято

#257 Kartashova M add lab8.1
  ISTbd-21/Kartashova M.V/lab-8.1/lab8.1.cpp
  ISTbd-21/Kartashova M.V/lab-8.1/list.h
  ISTbd-21/Kartashova M.V/lab-8.1/report8-1.md
Labels: ИСТбд-21, Принято

#259 Грязнов Е. лаб 8.1
  ISTbd-21/Gryaznov E.A/lab 8.1/lab8.1.cpp
  ISTbd-21/Gryaznov E.A/lab 8.1/Отчёт.md
Labels: ИСТбд-21, Принято

#267 add lab-8-2
  ISTbd-21/Ulianin A. A/lab8-2/List.h
  ISTbd-21/Ulianin A. A/lab8-2/ListIterator.h
  ISTbd-21/Ulianin A. A/lab8-2/Node.h
  ISTbd-21/Ulianin A. A/lab8-2/RandomGenerator.h
  ISTbd-21/Ulianin A. A/lab8-2/lab8-2.cpp
  ISTbd-21/Ulianin A. A/lab8-2/readMe.md
  ISTbd-21/Ulianin A. A/lab8-2/utils.h
Labels: ИСТбд-21, Принято

#277 Kartashova M add lab 8.2
  ISTbd-21/Kartashova M.V/lab-8.2/GeomProgression.h
  ISTbd-21/Kartashova M.V/lab-8.2/ListIterator.h
  ISTbd-21/Kartashova M.V/lab-8.2/Node.h
  ISTbd-21/Kartashova M.V/lab-8.2/lab8.2.cpp
  ISTbd-21/Kartashova M.V/lab-8.2/list.h
  ISTbd-21/Kartashova M.V/lab-8.2/report8-2.md
Labels: ИСТбд-21, Принято

#279 Tagashev I I - LAB-8.2 УБЕРИТЕ ЭТО ОТ МЕНЯ!
  ISTbd-22/Tagashev I.I/lab8.2/ArifmProgression.cpp
  ISTbd-22/Tagashev I.I/lab8.2/ArifmProgression.h
  ISTbd-22/Tagashev I.I/lab8.2/ListIterator.cpp
  ISTbd-22/Tagashev I.I/lab8.2/ListIterator.h
  ISTbd-22/Tagashev I.I/lab8.2/Node.cpp
  ISTbd-22/Tagashev I.I/lab8.2/Node.h
  ISTbd-22/Tagashev I.I/lab8.2/Source.cpp
  ISTbd-22/Tagashev I.I/lab8.2/list.cpp
  ISTbd-22/Tagashev I.I/lab8.2/list.h
Labels: ИСТбд-22, Принято

#272 Ushkova A lab 8.2
  ISTbd-22/Ushkova A. S/lab8.2/List.cpp
  ISTbd-22/Ushkova A. S/lab8.2/List.h
  ISTbd-22/Ushkova A. S/lab8.2/Node.cpp
  ISTbd-22/Ushkova A. S/lab8.2/geometric_generator.cpp
  ISTbd-22/Ushkova A. S/lab8.2/main.cpp
  ISTbd-22/Ushkova A. S/lab8.2/my_iterator.cpp
  ISTbd-22/Ushkova A. S/lab8.2/отчет.md
Labels: ИСТбд-22, Принято

#289 Gilmetdinova add lab 8.2
  ISTbd-21/GilmetdinovaED/lab-8.2/Generator.h
  ISTbd-21/GilmetdinovaED/lab-8.2/Math.h
  ISTbd-21/GilmetdinovaED/lab-8.2/Vector.h
  ISTbd-21/GilmetdinovaED/lab-8.2/VectorIterator.h
  ISTbd-21/GilmetdinovaED/lab-8.2/lab-8.2.cbp
  ISTbd-21/GilmetdinovaED/lab-8.2/main.cpp
  ISTbd-21/GilmetdinovaED/lab-8.2/report.md
Labels: ИСТбд-21, Принято

#290 Petrova A.A., add lab 8.1
  ISTbd-21/PetrovaAA/lab8.1/LinkedList.h
  ISTbd-21/PetrovaAA/lab8.1/main.cpp
  ISTbd-21/PetrovaAA/lab8.1/report8.1.md
Labels: ИСТбд-21, Принято

#298 Evtushenko add lab 0
  ISTbd-21/Evtushenko A. A/lab_0/main.cpp
  ISTbd-21/Evtushenko A. A/lab_0/readme.md
Labels: ИСТбд-21, Принято
