Repository Qui-Gon173/AiSD-2020, pull requests merged in 2021-01, with the labels that each got.

#303 Крахмалюк Д.А. лаба 5 переделанная
  ISTbd-22/Krakhmalyuk-D-A/lab5/aisd_lab5.cpp
Labels: ИСТбд-22, Ожидает проверки

#305 Крахмалюк Д.А. лаб 8.1
  ISTbd-22/Krakhmalyuk-D-A/lab8.1/aisd_lab8.1.cpp
  ISTbd-22/Krakhmalyuk-D-A/lab8.1/readme.md
Labels: ИСТбд-22, Ожидает проверки

#307 Iskhakov T I lab 8.1
  ISTbd-22/Iskhakov T. I/lab8.1/Queue.cpp
  ISTbd-22/Iskhakov T. I/lab8.1/Queue.h
  ISTbd-22/Iskhakov T. I/lab8.1/main.cpp
  ISTbd-22/Iskhakov T. I/lab8.1/report.md
Labels: ИСТбд-22, Ожидает проверки

#314 EgorovIE_lab8_1
  ISTbd-22/Egorov I.E/lab8_1/lab8.md
  ISTbd-22/Egorov I.E/lab8_1/vector.cpp
  ISTbd-22/Egorov I.E/lab8_1/vector.h
Labels: ИСТбд-22, Ожидает проверки

#304 Petrova A.A., add lab 8.2
  ISTbd-21/PetrovaAA/lab8.2/GeometricProgression.h
  ISTbd-21/PetrovaAA/lab8.2/Iterator.h
  ISTbd-21/PetrovaAA/lab8.2/LinkedList.h
  ISTbd-21/PetrovaAA/lab8.2/Node.h
  ISTbd-21/PetrovaAA/lab8.2/Properties.h
  ISTbd-21/PetrovaAA/lab8.2/main.cpp
  ISTbd-21/PetrovaAA/lab8.2/report8.2.md
Labels: ИСТбд-21, Принято

#306 Kashitsyna N.A. lab5
  ISTbd-21/KashitsynaNA/lab5/Array.txt
  ISTbd-21/KashitsynaNA/lab5/Source.cpp
  ISTbd-21/KashitsynaNA/lab5/first.txt
  ISTbd-21/KashitsynaNA/lab5/second.txt
  ISTbd-21/KashitsynaNA/lab5/Отчет.md
Labels: ИСТбд-21, Принято

#308 Kashitsyna N.A. lab6
  ISTbd-21/KashitsynaNA/lab6/Source1.cpp
  ISTbd-21/KashitsynaNA/lab6/Source2.cpp
  ISTbd-21/KashitsynaNA/lab6/Source3.cpp
  ISTbd-21/KashitsynaNA/lab6/Отчет.md
Labels: ИСТбд-21, Принято

#309 Kashitsyna N.A. lab7
  ISTbd-21/KashitsynaNA/lab7/Source.cpp
  ISTbd-21/KashitsynaNA/lab7/Отчет.md
Labels: ИСТбд-21, Принято

#313 Kashitsyna N.A. lab8.1
  ISTbd-21/KashitsynaNA/lab8.1/lab8.1.cpp
  ISTbd-21/KashitsynaNA/lab8.1/list.cpp
  ISTbd-21/KashitsynaNA/lab8.1/list.h
  ISTbd-21/KashitsynaNA/lab8.1/Отчет.md
Labels: ИСТбд-21, Принято

#330 Kashitsyna N.A. lab8.2
  ISTbd-21/KashitsynaNA/lab8.2/Elem.h
  ISTbd-21/KashitsynaNA/lab8.2/Generator.h
  ISTbd-21/KashitsynaNA/lab8.2/GeneratorIterator.h
  ISTbd-21/KashitsynaNA/lab8.2/OwnIterator.h
  ISTbd-21/KashitsynaNA/lab8.2/lab8.2.cpp
  ISTbd-21/KashitsynaNA/lab8.2/list.h
  ISTbd-21/KashitsynaNA/lab8.2/Отчет.md
Labels: ИСТбд-21, Принято

#278 Muraveva E.A. lab 1
  ISTbd-21/MyravevaEA/lab 1/README.md
  ISTbd-21/MyravevaEA/lab 1/лаба 1.cpp
Labels: ИСТбд-21, Принято

#325 Грязнов Е. лаб 8.2
  ISTbd-21/Gryaznov E.A/lab 8.2/ArifmProgression.h
  ISTbd-21/Gryaznov E.A/lab 8.2/ListIterator.h
  ISTbd-21/Gryaznov E.A/lab 8.2/Node.h
  ISTbd-21/Gryaznov E.A/lab 8.2/lab8.2.cpp
  ISTbd-21/Gryaznov E.A/lab 8.2/list.h
  ISTbd-21/Gryaznov E.A/lab 8.2/Отчет.md
Labels: ИСТбд-21, Принято

#354 EgorovIE_lab8_2
  ISTbd-22/Egorov I.E/lab8.2/ProgM.cpp
  ISTbd-22/Egorov I.E/lab8.2/gen.h
  ISTbd-22/Egorov I.E/lab8.2/iter.h
  ISTbd-22/Egorov I.E/lab8.2/lab8.md
  ISTbd-22/Egorov I.E/lab8.2/vector.h
Labels: ИСТбд-22, Ожидает проверки

#372 Iskhakov-E-A lab_8.1
  ISTbd-22/Iskhakov E A/lab_8.1/Source.cpp
  ISTbd-22/Iskhakov E A/lab_8.1/report.md
Labels: ИСТбд-22, Принято

#299 Evtushenko-A-A-lab1
  ISTbd-21/Evtushenko A A/lab1/Source.cpp
  ISTbd-21/Evtushenko A A/lab1/readme.md
Labels: ИСТбд-21, Принято

#318 Evtushenko-A-A-lab2
  ISTbd-21/Evtushenko A A/lab2/Source.cpp
  ISTbd-21/Evtushenko A A/lab2/readme.md
Labels: ИСТбд-21, Принято

#319 Evtushenko-A-A-lab3
  ISTbd-21/Evtushenko A. A/lab3/Source.cpp
  ISTbd-21/Evtushenko A. A/lab3/readme.md
Labels: ИСТбд-21, Принято

#326 Evtushenko A A lab4
  ISTbd-21/Evtushenko A. A/lab_4/main.cpp
  ISTbd-21/Evtushenko A. A/lab_4/readme.md
Labels: ИСТбд-21, Принято

#327 Evtushenko-A-A-lab5
  ISTbd-21/Evtushenko A. A/lab_5/Source.cpp
  ISTbd-21/Evtushenko A. A/lab_5/readme.md
Labels: ИСТбд-21, Принято

#329 Evtushenko A A lab6
  ISTbd-21/Evtushenko A. A/lab_6/main1.cpp
  ISTbd-21/Evtushenko A. A/lab_6/main2.cpp
  ISTbd-21/Evtushenko A. A/lab_6/main3.cpp
  ISTbd-21/Evtushenko A. A/lab_6/readme.md
Labels: ИСТбд-21, Принято

#352 Muraveva-E-A-lab-2
  ISTbd-21/Muraveva E A/lab 2/README.md
  ISTbd-21/Muraveva E A/lab 2/аисд лаба 2.cpp
Labels: ИСТбд-21, Принято

#331 Evtushenko A A lab7
  ISTbd-21/Evtushenko A. A/lab_7/main.cpp
  ISTbd-21/Evtushenko A. A/lab_7/readme.md
Labels: ИСТбд-21, Принято

#353 Muraveva-E-A-lab-3
  ISTbd-21/Muraveva E A/lab 3/README.md
  ISTbd-21/Muraveva E A/lab 3/аисд лаба 3.cpp
Labels: ИСТбд-21, Принято

#335 Latypov lab0
  ISTbd-21/LatypovA/lab0/README.md
  ISTbd-21/LatypovA/lab0/main.cpp
Labels: ИСТбд-21, Ожидает проверки

#345 shatalov-a-lab1
  ISTbd-21/Шаталов А.В/lab1/main.cpp
  ISTbd-21/Шаталов А.В/lab1/readme.md
Labels: ИСТбд-21, Ожидает проверки

#355 Muraveva-E-A-lab-4
  ISTbd-21/MyravevaEA/lab 4/README.md
  ISTbd-21/MyravevaEA/lab 4/лаба 4 аисд.cpp
Labels: ИСТбд-21, Ожидает проверки

#346 shatalov-a-lab2
  ISTbd-21/Шаталов А.В/lab2/main.cpp
  ISTbd-21/Шаталов А.В/lab2/readme.md
Labels: ИСТбд-21, Ожидает проверки

#336 Latypov lab1
  ISTbd-21/LatypovA/lab1/README.md
  ISTbd-21/LatypovA/lab1/main.cpp
Labels: ИСТбд-21, Ожидает проверки

#311 Efendiev Changed report for lab4
  ISTbd-21/EfendievSI/lab0/Readme.md
  ISTbd-21/EfendievSI/lab0/efensho_lab0.cpp
  ISTbd-21/EfendievSI/lab1/Readme.md
  ISTbd-21/EfendievSI/lab1/efensho_lab1.cpp
  ISTbd-21/EfendievSI/lab2/Readme.md
  ISTbd-21/EfendievSI/lab2/lab2.cpp
  ISTbd-21/EfendievSI/lab3/Readme.md
  ISTbd-21/EfendievSI/lab3/lab3.cpp
  ISTbd-21/EfendievSI/lab4/Readme.md
  ISTbd-21/EfendievSI/lab4/lab4.cpp
  ISTbd-21/EfendievSI/lab5/Readme.md
  ISTbd-21/EfendievSI/lab5/array.txt
  ISTbd-21/EfendievSI/lab5/lab5.cpp
  ISTbd-21/EfendievSI/lab6/1.cpp
  ISTbd-21/EfendievSI/lab6/2.cpp
  ISTbd-21/EfendievSI/lab6/3.cpp
  ISTbd-21/EfendievSI/lab6/Readme.md
  ISTbd-21/EfendievSI/lab7/Readme.md
  ISTbd-21/EfendievSI/lab7/lab7.cpp
  ISTbd-21/EfendievSI/lab8.1/Readme.md
  ISTbd-21/EfendievSI/lab8.1/lab8.1_4_4.cpp
  ISTbd-21/EfendievSI/lab8.1/list.h
  ISTbd-21/EfendievSI/lab8.2/Generator.h
  ISTbd-21/EfendievSI/lab8.2/List.h
  ISTbd-21/EfendievSI/lab8.2/ListIter.h
  ISTbd-21/EfendievSI/lab8.2/Node.h
  ISTbd-21/EfendievSI/lab8.2/Readme.md
  ISTbd-21/EfendievSI/lab8.2/lab8_2.cpp
  ISTbd-21/EfendievSI/lab8.2/utils.h
Labels: ИСТбд-21, Ожидает проверки

#357 Muraveva-E-A-lab-5
  ISTbd-21/MyravevaEA/lab 5/5 lab.md
  ISTbd-21/MyravevaEA/lab 5/File.txt
  ISTbd-21/MyravevaEA/lab 5/sort_1.txt
  ISTbd-21/MyravevaEA/lab 5/sort_2.txt
  ISTbd-21/MyravevaEA/lab 5/аисд лаба 5.cpp
Labels: ИСТбд-21, Ожидает проверки

#358 Muraveva-E-A-lab-6
  ISTbd-21/MyravevaEA/lab 6/6 lab.md
  ISTbd-21/MyravevaEA/lab 6/аисд лаба 6.2.cpp
  ISTbd-21/MyravevaEA/lab 6/аисд лаба 6.3.cpp
  ISTbd-21/MyravevaEA/lab 6/аисд лаба 6.cpp
Labels: ИСТбд-21, Ожидает проверки

#347 shatalov-a-lab3
  ISTbd-21/Шаталов А.В/lab3/main.cpp
  ISTbd-21/Шаталов А.В/lab3/readme.md
Labels: ИСТбд-21, Ожидает проверки

#312 Efendiev Added lab5
  ISTbd-21/EfendievSI/lab0/Readme.md
  ISTbd-21/EfendievSI/lab0/efensho_lab0.cpp
  ISTbd-21/EfendievSI/lab1/Readme.md
  ISTbd-21/EfendievSI/lab1/efensho_lab1.cpp
  ISTbd-21/EfendievSI/lab2/Readme.md
  ISTbd-21/EfendievSI/lab2/lab2.cpp
  ISTbd-21/EfendievSI/lab3/Readme.md
  ISTbd-21/EfendievSI/lab3/lab3.cpp
  ISTbd-21/EfendievSI/lab4/Readme.md
  ISTbd-21/EfendievSI/lab4/lab4.cpp
  ISTbd-21/EfendievSI/lab5/Readme.md
  ISTbd-21/EfendievSI/lab5/array.txt
  ISTbd-21/EfendievSI/lab5/lab5.cpp
  ISTbd-21/EfendievSI/lab6/1.cpp
  ISTbd-21/EfendievSI/lab6/2.cpp
  ISTbd-21/EfendievSI/lab6/3.cpp
  ISTbd-21/EfendievSI/lab6/Readme.md
  ISTbd-21/EfendievSI/lab7/Readme.md
  ISTbd-21/EfendievSI/lab7/lab7.cpp
  ISTbd-21/EfendievSI/lab8.1/Readme.md
  ISTbd-21/EfendievSI/lab8.1/lab8.1_4_4.cpp
  ISTbd-21/EfendievSI/lab8.1/list.h
  ISTbd-21/EfendievSI/lab8.2/Generator.h
  ISTbd-21/EfendievSI/lab8.2/List.h
  ISTbd-21/EfendievSI/lab8.2/ListIter.h
  ISTbd-21/EfendievSI/lab8.2/Node.h
  ISTbd-21/EfendievSI/lab8.2/Readme.md
  ISTbd-21/EfendievSI/lab8.2/lab8_2.cpp
  ISTbd-21/EfendievSI/lab8.2/utils.h
Labels: ИСТбд-21, Ожидает проверки

#315 Efendiev Added lab6
  ISTbd-21/EfendievSI/lab0/Readme.md
  ISTbd-21/EfendievSI/lab0/efensho_lab0.cpp
  ISTbd-21/EfendievSI/lab1/Readme.md
  ISTbd-21/EfendievSI/lab1/efensho_lab1.cpp
  ISTbd-21/EfendievSI/lab2/Readme.md
  ISTbd-21/EfendievSI/lab2/lab2.cpp
  ISTbd-21/EfendievSI/lab3/Readme.md
  ISTbd-21/EfendievSI/lab3/lab3.cpp
  ISTbd-21/EfendievSI/lab4/Readme.md
  ISTbd-21/EfendievSI/lab4/lab4.cpp
  ISTbd-21/EfendievSI/lab5/Readme.md
  ISTbd-21/EfendievSI/lab5/array.txt
  ISTbd-21/EfendievSI/lab5/lab5.cpp
  ISTbd-21/EfendievSI/lab6/1.cpp
  ISTbd-21/EfendievSI/lab6/2.cpp
  ISTbd-21/EfendievSI/lab6/3.cpp
  ISTbd-21/EfendievSI/lab6/Readme.md
  ISTbd-21/EfendievSI/lab7/Readme.md
  ISTbd-21/EfendievSI/lab7/lab7.cpp
  ISTbd-21/EfendievSI/lab8.1/Readme.md
  ISTbd-21/EfendievSI/lab8.1/lab8.1_4_4.cpp
  ISTbd-21/EfendievSI/lab8.1/list.h
  ISTbd-21/EfendievSI/lab8.2/Generator.h
  ISTbd-21/EfendievSI/lab8.2/List.h
  ISTbd-21/EfendievSI/lab8.2/ListIter.h
  ISTbd-21/EfendievSI/lab8.2/Node.h
  ISTbd-21/EfendievSI/lab8.2/Readme.md
  ISTbd-21/EfendievSI/lab8.2/lab8_2.cpp
  ISTbd-21/EfendievSI/lab8.2/utils.h
Labels: ИСТбд-21, Ожидает проверки

#359 Muraveva-E-A-lab-7
  ISTbd-21/MyravevaEA/lab 7/7 lab.md
  ISTbd-21/MyravevaEA/lab 7/аисд лаба 7.cpp
Labels: ИСТбд-21, Ожидает проверки

#337 Latypov lab2
  ISTbd-21/LatypovA/lab2/README.md
  ISTbd-21/LatypovA/lab2/main.cpp
Labels: ИСТбд-21, Ожидает проверки

#316 Efendiev Added lab7
  ISTbd-21/EfendievSI/lab0/Readme.md
  ISTbd-21/EfendievSI/lab0/efensho_lab0.cpp
  ISTbd-21/EfendievSI/lab1/Readme.md
  ISTbd-21/EfendievSI/lab1/efensho_lab1.cpp
  ISTbd-21/EfendievSI/lab2/Readme.md
  ISTbd-21/EfendievSI/lab2/lab2.cpp
  ISTbd-21/EfendievSI/lab3/Readme.md
  ISTbd-21/EfendievSI/lab3/lab3.cpp
  ISTbd-21/EfendievSI/lab4/Readme.md
  ISTbd-21/EfendievSI/lab4/lab4.cpp
  ISTbd-21/EfendievSI/lab5/Readme.md
  ISTbd-21/EfendievSI/lab5/array.txt
  ISTbd-21/EfendievSI/lab5/lab5.cpp
  ISTbd-21/EfendievSI/lab6/1.cpp
  ISTbd-21/EfendievSI/lab6/2.cpp
  ISTbd-21/EfendievSI/lab6/3.cpp
  ISTbd-21/EfendievSI/lab6/Readme.md
  ISTbd-21/EfendievSI/lab7/Readme.md
  ISTbd-21/EfendievSI/lab7/lab7.cpp
  ISTbd-21/EfendievSI/lab8.1/Readme.md
  ISTbd-21/EfendievSI/lab8.1/lab8.1_4_4.cpp
  ISTbd-21/EfendievSI/lab8.1/list.h
  ISTbd-21/EfendievSI/lab8.2/Generator.h
  ISTbd-21/EfendievSI/lab8.2/List.h
  ISTbd-21/EfendievSI/lab8.2/ListIter.h
  ISTbd-21/EfendievSI/lab8.2/Node.h
  ISTbd-21/EfendievSI/lab8.2/Readme.md
  ISTbd-21/EfendievSI/lab8.2/lab8_2.cpp
  ISTbd-21/EfendievSI/lab8.2/utils.h
Labels: ИСТбд-21, Ожидает проверки

#373 Evtushenko A A lab_8.1
  ISTbd-21/Evtushenko A. A/lab_8.1/lab8_1.cpp
  ISTbd-21/Evtushenko A. A/lab_8.1/print.h
  ISTbd-21/Evtushenko A. A/lab_8.1/report.md
  ISTbd-21/Evtushenko A. A/lab_8.1/stack.h
Labels: ИСТбд-21, Ожидает проверки

#374 Evtushenko-A-A-lab-8.2
  ISTbd-21/Evtushenko A. A/lab_8.2/generator.h
  ISTbd-21/Evtushenko A. A/lab_8.2/lab8.2.cpp
  ISTbd-21/Evtushenko A. A/lab_8.2/math.h
  ISTbd-21/Evtushenko A. A/lab_8.2/mycode.h
  ISTbd-21/Evtushenko A. A/lab_8.2/print.h
  ISTbd-21/Evtushenko A. A/lab_8.2/report.md
  ISTbd-21/Evtushenko A. A/lab_8.2/stack.h
  ISTbd-21/Evtushenko A. A/lab_8.2/stackIter.h
Labels: ИСТбд-21, Ожидает проверки

#348 shatalov-a-lab4
  ISTbd-21/Шаталов А.В/lab4/main.cpp
  ISTbd-21/Шаталов А.В/lab4/readme.md
Labels: ИСТбд-21, Ожидает проверки

#349 shatalov-a-lab5
  ISTbd-21/Шаталов А.В/lab5/main.cpp
  ISTbd-21/Шаталов А.В/lab5/readme.md
Labels: ИСТбд-21, Ожидает проверки

#350 shatalov-a-lab6
  ISTbd-21/Шаталов А.В/lab6/main1.cpp
  ISTbd-21/Шаталов А.В/lab6/main2.cpp
  ISTbd-21/Шаталов А.В/lab6/main3.cpp
  ISTbd-21/Шаталов А.В/lab6/readme.md
Labels: ИСТбд-21, Ожидает проверки

#339 Latypov lab4
  ISTbd-21/LatypovA/lab4/README.md
  ISTbd-21/LatypovA/lab4/main.cpp
Labels: ИСТбд-21, Ожидает проверки

#340 Latypov lab5
  ISTbd-21/LatypovA/lab5/README.md
  ISTbd-21/LatypovA/lab5/main.cpp
Labels: ИСТбд-21, Ожидает проверки

#341 Latypov lab6
  ISTbd-21/LatypovA/lab6/README.md
  ISTbd-21/LatypovA/lab6/ex1.cpp
  ISTbd-21/LatypovA/lab6/ex2.cpp
  ISTbd-21/LatypovA/lab6/ex3.cpp
Labels: ИСТбд-21, Ожидает проверки

#342 Latypov lab7
  ISTbd-21/LatypovA/lab7/README.md
  ISTbd-21/LatypovA/lab7/main.cpp
Labels: ИСТбд-21, Ожидает проверки

#351 shatalov-a-lab7
  ISTbd-21/Шаталов А.В/lab7/main.cpp
  ISTbd-21/Шаталов А.В/lab7/readme.md
Labels: ИСТбд-21, Ожидает проверки

#328 Efendiev Added lab8.2
  ISTbd-21/EfendievSI/lab0/Readme.md
  ISTbd-21/EfendievSI/lab0/efensho_lab0.cpp
  ISTbd-21/EfendievSI/lab1/Readme.md
  ISTbd-21/EfendievSI/lab1/efensho_lab1.cpp
  ISTbd-21/EfendievSI/lab2/Readme.md
  ISTbd-21/EfendievSI/lab2/lab2.cpp
  ISTbd-21/EfendievSI/lab3/Readme.md
  ISTbd-21/EfendievSI/lab3/lab3.cpp
  ISTbd-21/EfendievSI/lab4/Readme.md
  ISTbd-21/EfendievSI/lab4/lab4.cpp
  ISTbd-21/EfendievSI/lab5/Readme.md
  ISTbd-21/EfendievSI/lab5/array.txt
  ISTbd-21/EfendievSI/lab5/lab5.cpp
  ISTbd-21/EfendievSI/lab6/1.cpp
  ISTbd-21/EfendievSI/lab6/2.cpp
  ISTbd-21/EfendievSI/lab6/3.cpp
  ISTbd-21/EfendievSI/lab6/Readme.md
  ISTbd-21/EfendievSI/lab7/Readme.md
  ISTbd-21/EfendievSI/lab7/lab7.cpp
  ISTbd-21/EfendievSI/lab8.1/Readme.md
  ISTbd-21/EfendievSI/lab8.1/lab8.1_4_4.cpp
  ISTbd-21/EfendievSI/lab8.1/list.h
  ISTbd-21/EfendievSI/lab8.2/Generator.h
  ISTbd-21/EfendievSI/lab8.2/List.h
  ISTbd-21/EfendievSI/lab8.2/ListIter.h
  ISTbd-21/EfendievSI/lab8.2/Node.h
  ISTbd-21/EfendievSI/lab8.2/Readme.md
  ISTbd-21/EfendievSI/lab8.2/lab8_2.cpp
  ISTbd-21/EfendievSI/lab8.2/utils.h
Labels: ИСТбд-21, Ожидает проверки

#360 kalashnikov-lab-0
  ISTbd-21/KalashnikovMA/lab0/main.cpp
  ISTbd-21/KalashnikovMA/lab0/report.md
Labels: ИСТбд-21, Ожидает проверки

#361 Kalashnikov-lab-1
  ISTbd-21/KalashnikovMA/lab1/README.md
  ISTbd-21/KalashnikovMA/lab1/main.cpp
Labels: ИСТбд-21, Ожидает проверки

#362 Kalashnikov-lab-2
  ISTbd-21/KalashnikovMA/lab2/README.md
  ISTbd-21/KalashnikovMA/lab2/main.cpp
Labels: ИСТбд-21, Ожидает проверки

#363 Kalashnikov-lab-3
  ISTbd-21/KalashnikovMA/lab3/main.cpp
  ISTbd-21/KalashnikovMA/lab3/report.md
Labels: ИСТбд-21, Ожидает проверки

#364 Kalashnikov-lab-4
  ISTbd-21/KalashnikovMA/lab4/main.cpp
  ISTbd-21/KalashnikovMA/lab4/report.md
Labels: ИСТбд-21, Ожидает проверки

#365 Kalashnikov-lab-5
  ISTbd-21/KalashnikovMA/lab5/main.cpp
  ISTbd-21/KalashnikovMA/lab5/report.md
Labels: ИСТбд-21, Ожидает проверки

#366 Kalashnikov-lab-6
  ISTbd-21/KalashnikovMA/lab6/example1.cpp
  ISTbd-21/KalashnikovMA/lab6/example2.cpp
  ISTbd-21/KalashnikovMA/lab6/example3.cpp
  ISTbd-21/KalashnikovMA/lab6/report.md
Labels: ИСТбд-21, Ожидает проверки

#367 Kalashnikov-lab-7
  ISTbd-21/KalashnikovMA/lab7/main.cpp
  ISTbd-21/KalashnikovMA/lab7/report.md
Labels: ИСТбд-21, Ожидает проверки

#368 Kalashnikov-lab-8.1
  ISTbd-21/KalashnikovMA/lab8.1/Element.h
  ISTbd-21/KalashnikovMA/lab8.1/Report.md
  ISTbd-21/KalashnikovMA/lab8.1/Turn.cpp
  ISTbd-21/KalashnikovMA/lab8.1/Turn.h
  ISTbd-21/KalashnikovMA/lab8.1/lab8.1.cpp
Labels: ИСТбд-21, Ожидает проверки

#369 Kalashnikov-lab-8.2
  ISTbd-21/KalashnikovMA/lab8.2/Element.h
  ISTbd-21/KalashnikovMA/lab8.2/Generator.h
  ISTbd-21/KalashnikovMA/lab8.2/GeneratorIterator.h
  ISTbd-21/KalashnikovMA/lab8.2/Report.md
  ISTbd-21/KalashnikovMA/lab8.2/Turn.cpp
  ISTbd-21/KalashnikovMA/lab8.2/Turn.h
  ISTbd-21/KalashnikovMA/lab8.2/TurnIterator.cpp
  ISTbd-21/KalashnikovMA/lab8.2/TurnIterator.h
  ISTbd-21/KalashnikovMA/lab8.2/lab8.2.cpp
Labels: ИСТбд-21, Ожидает проверки

#343 Latypov lab8.1
  ISTbd-21/LatypovA/lab8.1/List.h
  ISTbd-21/LatypovA/lab8.1/Node.h
  ISTbd-21/LatypovA/lab8.1/README.md
  ISTbd-21/LatypovA/lab8.1/main.cpp
Labels: ИСТбд-21, Ожидает проверки

#344 Latypov lab8.2
  ISTbd-21/LatypovA/lab8.2/ArithmeticalGenerator.h
  ISTbd-21/LatypovA/lab8.2/List.h
  ISTbd-21/LatypovA/lab8.2/ListIterator.h
  ISTbd-21/LatypovA/lab8.2/Node.h
  ISTbd-21/LatypovA/lab8.2/README.md
  ISTbd-21/LatypovA/lab8.2/main.cpp
Labels: ИСТбд-21, Ожидает проверки

#317 Efendiev Added lab8.1
  ISTbd-21/EfendievSI/lab0/Readme.md
  ISTbd-21/EfendievSI/lab0/efensho_lab0.cpp
  ISTbd-21/EfendievSI/lab1/Readme.md
  ISTbd-21/EfendievSI/lab1/efensho_lab1.cpp
  ISTbd-21/EfendievSI/lab2/Readme.md
  ISTbd-21/EfendievSI/lab2/lab2.cpp
  ISTbd-21/EfendievSI/lab3/Readme.md
  ISTbd-21/EfendievSI/lab3/lab3.cpp
  ISTbd-21/EfendievSI/lab4/Readme.md
  ISTbd-21/EfendievSI/lab4/lab4.cpp
  ISTbd-21/EfendievSI/lab5/Readme.md
  ISTbd-21/EfendievSI/lab5/array.txt
  ISTbd-21/EfendievSI/lab5/lab5.cpp
  ISTbd-21/EfendievSI/lab6/1.cpp
  ISTbd-21/EfendievSI/lab6/2.cpp
  ISTbd-21/EfendievSI/lab6/3.cpp
  ISTbd-21/EfendievSI/lab6/Readme.md
  ISTbd-21/EfendievSI/lab7/Readme.md
  ISTbd-21/EfendievSI/lab7/lab7.cpp
  ISTbd-21/EfendievSI/lab8.1/Readme.md
  ISTbd-21/EfendievSI/lab8.1/lab8.1_4_4.cpp
  ISTbd-21/EfendievSI/lab8.1/list.h
  ISTbd-21/EfendievSI/lab8.2/Generator.h
  ISTbd-21/EfendievSI/lab8.2/List.h
  ISTbd-21/EfendievSI/lab8.2/ListIter.h
  ISTbd-21/EfendievSI/lab8.2/Node.h
  ISTbd-21/EfendievSI/lab8.2/Readme.md
  ISTbd-21/EfendievSI/lab8.2/lab8_2.cpp
  ISTbd-21/EfendievSI/lab8.2/utils.h
Labels: ИСТбд-21, Ожидает проверки

#320 add lab5
  ISTbd-21/AlekseenkoDV/lab5/main.cpp
  ISTbd-21/AlekseenkoDV/lab5/report.md
  ISTbd-21/AlekseenkoDV/lab5/text.txt
Labels: ИСТбд-21, Ожидает проверки

#321 add lab6
  ISTbd-21/AlekseenkoDV/lab6/main1.cpp
  ISTbd-21/AlekseenkoDV/lab6/main2.cpp
  ISTbd-21/AlekseenkoDV/lab6/main3.cpp
  ISTbd-21/AlekseenkoDV/lab6/report.md
Labels: ИСТбд-21, Ожидает проверки

#310 Osipov-K-S-lab8.2
  ISTbd-22/Осипов К.С/lab8-2/DoubleList.h
  ISTbd-22/Осипов К.С/lab8-2/ExponentialGenerator.h
  ISTbd-22/Осипов К.С/lab8-2/ListIterator.h
  ISTbd-22/Осипов К.С/lab8-2/README.md
  ISTbd-22/Осипов К.С/lab8-2/main.cpp
Labels: ИСТбд-22, Ожидает проверки

#375 Farsiev lab0
  ISTbd-22/Farsiev A.R/lab0/main.cpp
  ISTbd-22/Farsiev A.R/lab0/Отчет.md
Labels: ИСТбд-22, Ожидает проверки

#376 Farsiev-lab1
  ISTbd-22/Farsiev A.R/lab1/lab-1.cbp
  ISTbd-22/Farsiev A.R/lab1/lab-1.depend
  ISTbd-22/Farsiev A.R/lab1/lab-1.layout
  ISTbd-22/Farsiev A.R/lab1/main.cpp
  ISTbd-22/Farsiev A.R/lab1/Отчет.md
Labels: ИСТбд-22, Ожидает проверки

#377 Farsiev-lab2
  ISTbd-22/Farsiev A.R/lab2/main.cpp
  ISTbd-22/Farsiev A.R/lab2/Отчет.md
Labels: ИСТбд-22, Принято

#378 Farsiev-lab3
  ISTbd-22/Farsiev A.R/lab3/main.cpp
  ISTbd-22/Farsiev A.R/lab3/Отчет.md
Labels: ИСТбд-22, Принято

#379 Farsiev-lab4
  ISTbd-22/Farsiev A.R/lab4/main.cpp
  ISTbd-22/Farsiev A.R/lab4/Отчет.md
Labels: ИСТбд-22, Ожидает проверки

#380 Farsiev-lab5
  ISTbd-22/Farsiev A.R/lab5/lab5.cpp
  ISTbd-22/Farsiev A.R/lab5/Отчет.md
Labels: ИСТбд-22, Ожидает проверки

#381 Farsiev-lab6
  ISTbd-22/Farsiev A.R/lab6/1.cpp
  ISTbd-22/Farsiev A.R/lab6/2.cpp
  ISTbd-22/Farsiev A.R/lab6/3.cpp
  ISTbd-22/Farsiev A.R/lab6/Отчет.md
Labels: ИСТбд-22, Ожидает проверки

#384 Farsiev-lab7
  ISTbd-22/Farsiev A.R/Lab7/lab7.cpp
  ISTbd-22/Farsiev A.R/Lab7/Отчет.md
Labels: ИСТбд-22, Принято

#322 add lab7
  ISTbd-21/AlekseenkoDV/lab7/hanoiTower.jpg
  ISTbd-21/AlekseenkoDV/lab7/main.cpp
  ISTbd-21/AlekseenkoDV/lab7/report.md
Labels: ИСТбд-21, Ожидает проверки

#323 add lab8.1
  ISTbd-21/AlekseenkoDV/lab8.1/main.cpp
  ISTbd-21/AlekseenkoDV/lab8.1/readme.md
Labels: ИСТбд-21, Ожидает проверки

#324 add lab8.2
  ISTbd-21/AlekseenkoDV/lab8.2/geometric_progression_generator.h
  ISTbd-21/AlekseenkoDV/lab8.2/main.cpp
  ISTbd-21/AlekseenkoDV/lab8.2/readme.md
  ISTbd-21/AlekseenkoDV/lab8.2/stack.h
  ISTbd-21/AlekseenkoDV/lab8.2/stack_functions.h
  ISTbd-21/AlekseenkoDV/lab8.2/stack_iterator.h
Labels: ИСТбд-21, Ожидает проверки

#388 Крахмалюк Д.А. лаба 8.2
  ISTbd-22/Krakhmalyuk-D-A/lab8.2/aisd_lab8.2.cpp
  ISTbd-22/Krakhmalyuk-D-A/lab8.2/readme.md
Labels: ИСТбд-22, Принято

#390 Kuchina-lab8.2
  ISTbd-22/Kuchina A. A/lab8.2/List.h
  ISTbd-22/Kuchina A. A/lab8.2/Node.h
  ISTbd-22/Kuchina A. A/lab8.2/main.cpp
  ISTbd-22/Kuchina A. A/lab8.2/my_geo_generator.h
  ISTbd-22/Kuchina A. A/lab8.2/my_iterator.h
  ISTbd-22/Kuchina A. A/lab8.2/Отчет.md
Labels: ИСТбд-22, Ожидает проверки

#385 Iskhakov T. I. lab 8.2
  ISTbd-22/Iskhakov T. I/lab8.2/GeometricProgressionGenerator.cpp
  ISTbd-22/Iskhakov T. I/lab8.2/GeometricProgressionGenerator.h
  ISTbd-22/Iskhakov T. I/lab8.2/Node.h
  ISTbd-22/Iskhakov T. I/lab8.2/Queue.cpp
  ISTbd-22/Iskhakov T. I/lab8.2/Queue.h
  ISTbd-22/Iskhakov T. I/lab8.2/QueueIterator.cpp
  ISTbd-22/Iskhakov T. I/lab8.2/QueueIterator.h
  ISTbd-22/Iskhakov T. I/lab8.2/main.cpp
  ISTbd-22/Iskhakov T. I/lab8.2/report.md
Labels: ИСТбд-22, Ожидает проверки

#387 Farsiev-lab8.1
  ISTbd-22/Farsiev A.R/lab8.1/8.1.cpp
  ISTbd-22/Farsiev A.R/lab8.1/list.h
  ISTbd-22/Farsiev A.R/lab8.1/Отчет.md
Labels: ИСТбд-22, Ожидает проверки

#400 Farsiev-lab8.2
  ISTbd-22/Farsiev A.R/lab8.2/List.h
  ISTbd-22/Farsiev A.R/lab8.2/ListIterator.h
  ISTbd-22/Farsiev A.R/lab8.2/Node.h
  ISTbd-22/Farsiev A.R/lab8.2/RandomGenerator.h
  ISTbd-22/Farsiev A.R/lab8.2/lab8.2.cpp
  ISTbd-22/Farsiev A.R/lab8.2/utils.h
  ISTbd-22/Farsiev A.R/lab8.2/Отчет.md
Labels: ИСТбд-22, Принято

#389 Шарапов А.Н. Лаб 0
  ISTbd-22/Sharapov A.N/lab0/main.cpp
  ISTbd-22/Sharapov A.N/lab0/Отчет.md
Labels: ИСТбд-22, Ожидает проверки

#386 Doronkin A.N lab 8.1
  ISTbd-22/Doronkin A.N/lab8.1/main.cpp
  ISTbd-22/Doronkin A.N/lab8.1/Отчет.md
Labels: ИСТбд-22, Ожидает проверки

#280 Sedykh-N-V-lab-8.1
  ISTbd-22/Sedykh N. V/lab8.1/Stack.cpp
  ISTbd-22/Sedykh N. V/lab8.1/Stack.h
  ISTbd-22/Sedykh N. V/lab8.1/lab8.1.cpp
  ISTbd-22/Sedykh N. V/lab8.1/отчет.md
Labels: ИСТбд-22, Принято

#383 Miridonov Lab 8.1
  ISTbd-22/Miridonov-P-A/lab8-1/main.cpp
  ISTbd-22/Miridonov-P-A/lab8-1/Отчет.md
Labels: ИСТбд-22, Ожидает проверки

#391 Шарапов А.Н. Лаб 1
  ISTbd-22/Sharapov A.N/lab1/main.cpp
  ISTbd-22/Sharapov A.N/lab1/Отчет№1.md
Labels: ИСТбд-22, Принято

#392 Шарапов А.Н. Лаб 2
  ISTbd-22/Sharapov A.N/lab2/main.cpp
  ISTbd-22/Sharapov A.N/lab2/Отчет№2.md
Labels: ИСТбд-22, Принято

#393 Шарапов А.Н. Лаб 3
  ISTbd-22/Sharapov A.N/lab3/main.cpp
  ISTbd-22/Sharapov A.N/lab3/Отчет№3.md
Labels: ИСТбд-22, Принято

#394 Шарапов А.Н. Лаб 4
  ISTbd-22/Sharapov A.N/lab4/main.cpp
  ISTbd-22/Sharapov A.N/lab4/Отчет№4.md
Labels: ИСТбд-22, Принято

#395 Шарапов А.Н. Лаб 5
  ISTbd-22/Sharapov A.N/lab5/main.cpp
  ISTbd-22/Sharapov A.N/lab5/Отчет№5.md
Labels: ИСТбд-22, Принято

#396 Шарапов А.Н. Лаб 6
  ISTbd-22/Sharapov A.N/lab6/main1.cpp
  ISTbd-22/Sharapov A.N/lab6/main2.cpp
  ISTbd-22/Sharapov A.N/lab6/main3.cpp
  ISTbd-22/Sharapov A.N/lab6/Отчет№6.md
Labels: ИСТбд-22, Принято

#397 Шарапов А.Н. Лаб 7
  ISTbd-22/Sharapov A.N/lab7/main.cpp
  ISTbd-22/Sharapov A.N/lab7/Отчет№7.md
Labels: ИСТбд-22, Принято

#398 Шарапов А.Н. Лаб 8.1
  ISTbd-22/Sharapov A.N/lab8.1/lab8.1.cpp
  ISTbd-22/Sharapov A.N/lab8.1/Отчет№8.1.md
Labels: ИСТбд-22, Принято

#399 Шарапов А.Н. Лаб 8.2
  ISTbd-22/Sharapov A.N/lab8.2/FibGenerator.h
  ISTbd-22/Sharapov A.N/lab8.2/Func.h
  ISTbd-22/Sharapov A.N/lab8.2/Vector.h
  ISTbd-22/Sharapov A.N/lab8.2/VectorIterator.h
  ISTbd-22/Sharapov A.N/lab8.2/main.cpp
  ISTbd-22/Sharapov A.N/lab8.2/Отчет№8.2.md
Labels: ИСТбд-22, Принято

#401 Doronkin A.N lab8.2
  ISTbd-22/Doronkin A.N/lab8.2/exponential_function_number_generator.h
  ISTbd-22/Doronkin A.N/lab8.2/main.cpp
  ISTbd-22/Doronkin A.N/lab8.2/stack.h
  ISTbd-22/Doronkin A.N/lab8.2/stack_functions.h
  ISTbd-22/Doronkin A.N/lab8.2/stack_iterator.h
  ISTbd-22/Doronkin A.N/lab8.2/Отчет.md
Labels: ИСТбд-22, Принято

#410 Miridonov lab 8-2
  ISTbd-22/Miridonov-P-A/lab8-2/ExponentialFunctionGenerator.h
  ISTbd-22/Miridonov-P-A/lab8-2/List.h
  ISTbd-22/Miridonov-P-A/lab8-2/Node.h
  ISTbd-22/Miridonov-P-A/lab8-2/main.cpp
  ISTbd-22/Miridonov-P-A/lab8-2/my_iterator.h
  ISTbd-22/Miridonov-P-A/lab8-2/Отчет.md
Labels: ИСТбд-22, Принято

#411 Арсланова лабы 0-7
  ISTbd-22/Arslanova A. A/lab0/main.cpp
  ISTbd-22/Arslanova A. A/lab0/отчет0.md
  ISTbd-22/Arslanova A. A/lab1-2/main.cpp
  ISTbd-22/Arslanova A. A/lab1-2/отчет1-2.md
  ISTbd-22/Arslanova A. A/lab3/main.cpp
  ISTbd-22/Arslanova A. A/lab3/отчет3.md
  ISTbd-22/Arslanova A. A/lab4/main.cpp
  ISTbd-22/Arslanova A. A/lab4/отчет4.md
  ISTbd-22/Arslanova A. A/lab5/lab5отчет.md
  ISTbd-22/Arslanova A. A/lab5/лаба 5.cpp
  ISTbd-22/Arslanova A. A/lab6/lab6отчет.md
  ISTbd-22/Arslanova A. A/lab6/лаба 6.1 аисд.cpp
  ISTbd-22/Arslanova A. A/lab6/лаба 6.2 аисд.cpp
  ISTbd-22/Arslanova A. A/lab6/лаба 6.3 аисд.cpp
  ISTbd-22/Arslanova A. A/lab7/lab7отчет.md
  ISTbd-22/Arslanova A. A/lab7/лаба 7 аисд.cpp
Labels: ИСТбд-22, Принято

#409 Akchurin-I-R-lab-7
  ISTbd-22/Akchurin I.R/lab 7/README.md
  ISTbd-22/Akchurin I.R/lab 7/lab 7.cpp
Labels: ИСТбд-22, Ожидает проверки

#412 Арсланова ИСТбд-22 лаба 8.1
  ISTbd-22/Arslanova A. A/Node.h
  ISTbd-22/Arslanova A. A/аисд 8.cpp
  ISTbd-22/Arslanova A. A/отчет.md
Labels: ИСТбд-22, Принято

#413 Арсланова ИСТбд-22 лаба 8.2
  ISTbd-22/Arslanova A. A/List.h
  ISTbd-22/Arslanova A. A/ListIterator.h
  ISTbd-22/Arslanova A. A/Node.h
  ISTbd-22/Arslanova A. A/RandomGenerator.h
  ISTbd-22/Arslanova A. A/lab8.2.cpp
  ISTbd-22/Arslanova A. A/utils.h
  ISTbd-22/Arslanova A. A/Отчет.md
Labels: ИСТбд-22, Ожидает проверки

#402 Akchurin-I-R-lab-0
  ISTbd-22/Akchurin I.R/lab 0/README.md
  ISTbd-22/Akchurin I.R/lab 0/main.cpp
  ISTbd-22/Akchurin I.R/lab 1/README.md
  ISTbd-22/Akchurin I.R/lab 1/lab 1.cpp
Labels: ИСТбд-22, Принято

#404 Akchurin-I-R-lab-2
  ISTbd-22/Akchurin I.R/lab 2/README.md
  ISTbd-22/Akchurin I.R/lab 2/lab 2.cpp
Labels: ИСТбд-22, Принято

#405 Akchurin-I-R-lab-3
  ISTbd-22/Akchurin I.R/lab 3/README.md
  ISTbd-22/Akchurin I.R/lab 3/lab 3.cpp
Labels: ИСТбд-22, Принято

#406 Akchurin-I-R-lab-4
  ISTbd-22/Akchurin I.R/lab 4/README.md
  ISTbd-22/Akchurin I.R/lab 4/lab 4.cpp
Labels: ИСТбд-22, Принято

#407 Akchurin-I-R-lab-5
  ISTbd-22/Akchurin I.R/lab 5/Lab 5.cpp
  ISTbd-22/Akchurin I.R/lab 5/README.md
  ISTbd-22/Akchurin I.R/lab 5/array.txt
Labels: ИСТбд-22, Принято

#408 Akchurin-I-R-lab-6
  ISTbd-22/Akchurin I.R/lab 6/README.md
  ISTbd-22/Akchurin I.R/lab 6/main 1.cpp
  ISTbd-22/Akchurin I.R/lab 6/main 2.cpp
  ISTbd-22/Akchurin I.R/lab 6/main 3.cpp
Labels: ИСТбд-22, Принято

#415 Akchurin-I-R-lab-8.1
  ISTbd-22/Akchurin I.R/lab 8.1/8.1.cpp
  ISTbd-22/Akchurin I.R/lab 8.1/Element.h
  ISTbd-22/Akchurin I.R/lab 8.1/Queue.cpp
  ISTbd-22/Akchurin I.R/lab 8.1/Queue.h
  ISTbd-22/Akchurin I.R/lab 8.1/README.md
Labels: ИСТбд-22, Принято

#416 Akchurin-I-R-lab-8.2
  ISTbd-22/Akchurin I.R/lab 8.2/Element.h
  ISTbd-22/Akchurin I.R/lab 8.2/Generator.h
  ISTbd-22/Akchurin I.R/lab 8.2/GeneratorIterator.h
  ISTbd-22/Akchurin I.R/lab 8.2/Queue.cpp
  ISTbd-22/Akchurin I.R/lab 8.2/Queue.h
  ISTbd-22/Akchurin I.R/lab 8.2/QueueIterator.cpp
  ISTbd-22/Akchurin I.R/lab 8.2/QueueIterator.h
  ISTbd-22/Akchurin I.R/lab 8.2/README.md
  ISTbd-22/Akchurin I.R/lab 8.2/lab 8.2.cpp
Labels: ИСТбд-22, Принято

#417 Iskhakov E A lab_8.2
  ISTbd-22/Iskhakov E A/lab_8.2/List.h
  ISTbd-22/Iskhakov E A/lab_8.2/ListIterator.h
  ISTbd-22/Iskhakov E A/lab_8.2/Node.h
  ISTbd-22/Iskhakov E A/lab_8.2/edw8.2.cpp
  ISTbd-22/Iskhakov E A/lab_8.2/math.h
  ISTbd-22/Iskhakov E A/lab_8.2/report.md
Labels: ИСТбд-22, Принято
